// Seed spot data. See HANDOFF.md for provenance notes — most of these were
// re-verified against real sources, a few were corrected (see git history).
export const SPOTS = {
  trestles: { name: 'Lower Trestles', region: 'San Clemente, CA', blurb: 'Cobblestone point wrapping into long, workable walls. Best before the wind fills in.', lat: 33.3825, lon: -117.5972, offshoreDeg: 60 },
  blacks: { name: 'Blacks Beach', region: 'La Jolla, CA', blurb: 'Deep submarine canyon keeps it offshore-groomed most of the day. Powerful and hollow.', lat: 32.8991, lon: -117.2528, offshoreDeg: 90 },
  rincon: { name: 'Rincon', region: 'Santa Barbara, CA', blurb: 'Long, playful walls peeling down the point. Small today, but silky smooth.', lat: 34.3739, lon: -119.4763, offshoreDeg: 350 },
  wedge: { name: 'The Wedge', region: 'Newport Beach, CA', blurb: 'Ledgy, close-interval peaks off the jetty. Heavy, and not for the faint of heart.', lat: 33.5952, lon: -117.8822, offshoreDeg: 30 },
  pipeline: { name: 'Pipeline', region: 'Oahu, Hawaii', blurb: "World-famous reef barrel on the North Shore. Heavy, shallow, and unforgiving when it's on.", lat: 21.6647, lon: -158.0538, offshoreDeg: 200 },
  teahupoo: { name: "Teahupo'o", region: 'Tahiti, French Polynesia', blurb: 'One of the heaviest, thickest waves on the planet, breaking over shallow coral.', lat: -17.8570, lon: -149.2680, offshoreDeg: 20 },
  jbay: { name: 'Jeffreys Bay', region: 'Eastern Cape, South Africa', blurb: 'Long, high-speed right point — one of the best walls in the world when it lines up.', lat: -34.0489, lon: 24.9087, offshoreDeg: 325 },
  uluwatu: { name: 'Uluwatu', region: 'Bali, Indonesia', blurb: "Dramatic reef break beneath a clifftop temple, with several sections down the point.", lat: -8.8290, lon: 115.0870, offshoreDeg: 50 },
  snapper: { name: 'Snapper Rocks', region: 'Gold Coast, Australia', blurb: 'The Superbank — impossibly long, fast right points when the sand banks line up.', lat: -28.1590, lon: 153.5470, offshoreDeg: 250 },
  nazare: { name: 'Nazaré', region: 'Portugal', blurb: 'Home to some of the biggest waves ever surfed, thanks to an underwater canyon offshore.', lat: 39.6033, lon: -9.0705, offshoreDeg: 85 },
  chicama: { name: 'Chicama', region: 'La Libertad, Peru', blurb: 'The longest left-hand point wave in the world — rides can last over a minute.', lat: -7.7000, lon: -79.4500, offshoreDeg: 135 },
  raglan: { name: 'Raglan', region: 'Waikato, New Zealand', blurb: 'Classic left point break, one of the most consistent walls in the Southern Hemisphere.', lat: -37.8010, lon: 174.8710, offshoreDeg: 95 },
  puertoescondido: { name: 'Puerto Escondido', region: 'Oaxaca, Mexico', blurb: "Nicknamed the Mexican Pipeline — a powerful, sandy-bottom beach break barrel.", lat: 15.8720, lon: -97.0767, offshoreDeg: 15 },
  hossegor: { name: 'Hossegor', region: 'France', blurb: 'Punchy, powerful Atlantic beach breaks that host a stop on the world tour.', lat: 43.6640, lon: -1.4400, offshoreDeg: 90 },
  mundaka: { name: 'Mundaka', region: 'Basque Country, Spain', blurb: 'A world-class left river-mouth wave that peels around a sandbar.', lat: 43.4070, lon: -2.6990, offshoreDeg: 180 },
  cloudbreak: { name: 'Cloudbreak', region: 'Mamanuca Islands, Fiji', blurb: 'A world-class reef pass left, breaking over shallow coral in the open ocean.', lat: -17.8600, lon: 177.2000, offshoreDeg: 130 },
  skeletonbay: { name: 'Skeleton Bay', region: 'Namibia', blurb: 'A freakishly long, mechanical sand-point left along a remote desert coastline.', lat: -22.9590, lon: 14.4930, offshoreDeg: 165 },
  pavones: { name: 'Pavones', region: 'Golfo Dulce, Costa Rica', blurb: 'One of the longest lefts in the world, wrapping into a jungle-lined bay.', lat: 8.3830, lon: -83.1500, offshoreDeg: 25 },
  fistral: { name: 'Fistral Beach', region: 'Newquay, Cornwall, UK', blurb: "The UK's best-known beach break, exposed to the full force of the Atlantic.", lat: 50.4160, lon: -5.1020, offshoreDeg: 90 },
  anchorpoint: { name: 'Anchor Point', region: 'Taghazout, Morocco', blurb: 'A classic North African right point, long and mellow when it wraps in clean.', lat: 30.5460, lon: -9.7100, offshoreDeg: 85 },
  margaretriver: { name: 'Margaret River', region: 'Western Australia', blurb: 'Powerful, chilly reef and point breaks along a wild stretch of coastline.', lat: -33.9750, lon: 115.0750, offshoreDeg: 90 },
  montauk: { name: 'Montauk', region: 'New York, USA', blurb: 'Classic East Coast beach and reef breaks at the tip of Long Island.', lat: 41.0500, lon: -71.9200, offshoreDeg: 330 },
  arugambay: { name: 'Arugam Bay', region: 'Sri Lanka', blurb: "A long, sandy-bottomed right point on Sri Lanka's east coast.", lat: 6.8400, lon: 81.8300, offshoreDeg: 270 },
  gland: { name: 'G-Land', region: 'East Java, Indonesia', blurb: 'A legendary, remote left reef break inside a jungle bay.', lat: -8.7304, lon: 114.3526, offshoreDeg: 35 },
  siargao: { name: 'Siargao (Cloud 9)', region: 'Philippines', blurb: 'A hollow, powerful reef pass that put the Philippines on the surfing map.', lat: 9.8000, lon: 126.1660, offshoreDeg: 270 },
  ericeira: { name: 'Ericeira', region: 'Portugal', blurb: 'A World Surfing Reserve with a cluster of quality points and reefs.', lat: 38.9630, lon: -9.4160, offshoreDeg: 90 },
  desertpoint: { name: 'Desert Point', region: 'Lombok, Indonesia', blurb: 'One of the fastest, longest tube rides on Earth, over sharp reef.', lat: -8.8900, lon: 116.0400, offshoreDeg: 60 },
  tofino: { name: 'Tofino', region: 'Vancouver Island, Canada', blurb: 'Cold-water Pacific beach breaks framed by old-growth rainforest.', lat: 49.1530, lon: -125.9066, offshoreDeg: 90 },
  joaquina: { name: 'Joaquina', region: 'Florianópolis, Brazil', blurb: 'A popular sandy beach break on Floripa island, consistent and crowd-friendly.', lat: -27.6280, lon: -48.4480, offshoreDeg: 270 },
  puntadelobos: { name: 'Punta de Lobos', region: 'Pichilemu, Chile', blurb: "A powerful, rocky left point on Chile's rugged central coast.", lat: -34.4110, lon: -72.0270, offshoreDeg: 90 },
  shonan: { name: 'Shonan', region: 'Kanagawa, Japan', blurb: "Tokyo's home break — accessible and consistent, a train ride from the city.", lat: 35.3060, lon: 139.4870, offshoreDeg: 0 },
  kovalam: { name: 'Kovalam', region: 'Kerala, India', blurb: "A mellow beach break on India's southwestern coast, warm water year-round.", lat: 8.4004, lon: 76.9787, offshoreDeg: 90 },
  caesarea: { name: 'Caesarea', region: 'Israel', blurb: 'A Mediterranean reef break beside the ruins of an ancient Roman harbor.', lat: 32.5000, lon: 34.9040, offshoreDeg: 90 },
  elcotillo: { name: 'El Cotillo', region: 'Fuerteventura, Canary Islands', blurb: "Wind-sculpted beach breaks on the island's rugged north coast.", lat: 28.6800, lon: -14.0080, offshoreDeg: 165 },
  popoyo: { name: 'Popoyo', region: 'Nicaragua', blurb: "A hollow reef break on Nicaragua's Pacific coast, offshore almost every morning.", lat: 11.4731, lon: -86.1270, offshoreDeg: 90 },
  santacatalina: { name: 'Santa Catalina', region: 'Panama', blurb: "A powerful, rocky point break on Panama's Pacific coast.", lat: 7.6330, lon: -81.2680, offshoreDeg: 85 },
  deadmans: { name: 'Deadmans', region: 'Denmark', blurb: "A cold-water North Sea break in Denmark's surf region, best with a groundswell and light wind.", lat: 57.0500, lon: 8.5100, offshoreDeg: 90 },
  muine: { name: 'Mui Ne', region: 'Vietnam', blurb: 'A wind-exposed stretch of coast better known for kitesurfing, but surfable too.', lat: 10.9330, lon: 108.2830, offshoreDeg: 293 },
  laentrada: { name: 'La Entrada', region: 'Ecuador', blurb: "A sandy beach break at the north end of the Olón beach stretch, gentle and beginner-friendly.", lat: -1.7700, lon: -80.7700, offshoreDeg: 90 },
  montoya: { name: 'Montoya', region: 'Punta del Este, Uruguay', blurb: "A rocky point near Punta del Este, one of Uruguay's better-known breaks.", lat: -34.9500, lon: -54.9300, offshoreDeg: 350 },
  darne: { name: 'Darne', region: 'Mauritius', blurb: "A remote left reef break behind Île des Deux Cocos, inside the island's fringing coral.", lat: -20.4200, lon: 57.7000, offshoreDeg: 0 },
  capesolander: { name: 'Cape Solander', region: 'Sydney, Australia', blurb: "An exposed ledge break on the cliffs at Sydney's Kurnell headland.", lat: -34.0010, lon: 151.2330, offshoreDeg: 270 },
  masnou: { name: 'Masnou', region: 'Catalonia, Spain', blurb: 'A Mediterranean beach break just north of Barcelona, small but rideable on a good day.', lat: 41.4780, lon: 2.3160, offshoreDeg: 315 },
  capomarina: { name: 'Capo Marina', region: 'Genoa, Italy', blurb: 'A rocky point break on the Ligurian coast near Genoa.', lat: 44.4000, lon: 8.9500, offshoreDeg: 5 },

  // Second batch — added on request to expand geographic coverage. Same caveat as the
  // original 44: reasonable estimates from available sources, not surveyed. Coordinates for
  // the least-documented of these (Macaronis, Riyue Bay) were verified against cited sources;
  // Lagundri Bay and Jinzun are lower-confidence estimates (no precise published coordinates
  // found) placed near the nearest documented reference point.
  malibu: { name: 'Malibu (Surfrider Beach)', region: 'California, USA', blurb: 'A classic, mechanical right point that helped define modern longboarding.', lat: 34.0369, lon: -118.6786, offshoreDeg: 0 },
  steamerlane: { name: 'Steamer Lane', region: 'Santa Cruz, CA', blurb: 'A punchy reef/point off a cliffside lighthouse, the heart of Santa Cruz surfing.', lat: 36.9519, lon: -122.0247, offshoreDeg: 30 },
  mavericks: { name: 'Mavericks', region: 'Half Moon Bay, CA', blurb: 'A cold-water big-wave reef that only wakes up on serious winter swells.', lat: 37.4913, lon: -122.5025, offshoreDeg: 90 },
  waimeabay: { name: 'Waimea Bay', region: 'Oahu, Hawaii', blurb: "Hawaii's original big-wave proving ground, dormant until the swell is massive.", lat: 21.6392, lon: -158.0656, offshoreDeg: 180 },
  sunsetbeach: { name: 'Sunset Beach', region: 'Oahu, Hawaii', blurb: 'A shifting, powerful North Shore peak that punishes poor positioning.', lat: 21.6754, lon: -158.0400, offshoreDeg: 180 },
  honoluabay: { name: 'Honolua Bay', region: 'Maui, Hawaii', blurb: 'A picture-perfect right point wrapping into a protected jungle bay.', lat: 21.0067, lon: -156.6403, offshoreDeg: 135 },
  hookipa: { name: 'Hookipa', region: 'Maui, Hawaii', blurb: 'Powerful reef break better known today as a windsurfing/kite mecca.', lat: 20.9330, lon: -156.3580, offshoreDeg: 180 },
  sayulita: { name: 'Sayulita', region: 'Nayarit, Mexico', blurb: 'A friendly, playful beach and point break inside a laid-back fishing village.', lat: 20.8700, lon: -105.4419, offshoreDeg: 45 },
  barradelacruz: { name: 'Barra de la Cruz', region: 'Oaxaca, Mexico', blurb: 'A world-class right point through a village-owned reserve, long and rippable.', lat: 15.9280, lon: -96.0670, offshoreDeg: 0 },
  playahermosa: { name: 'Playa Hermosa', region: 'Puntarenas, Costa Rica', blurb: "Costa Rica's most consistent beach break, powerful and popular with pros in training.", lat: 9.5480, lon: -84.5820, offshoreDeg: 45 },
  witchsrock: { name: "Witch's Rock", region: 'Guanacaste, Costa Rica', blurb: 'A remote national-park beach break made famous by Endless Summer II.', lat: 10.7990, lon: -85.6870, offshoreDeg: 90 },
  salsabrava: { name: 'Salsa Brava', region: 'Puerto Viejo, Costa Rica', blurb: "Costa Rica's heaviest wave, a shallow Caribbean reef pass not for beginners.", lat: 9.6550, lon: -82.7530, offshoreDeg: 270 },
  elsunzal: { name: 'El Sunzal', region: 'La Libertad, El Salvador', blurb: "A long, forgiving right point — one of Central America's best learn-to-surf waves.", lat: 13.4930, lon: -89.4460, offshoreDeg: 0 },
  puntaroca: { name: 'Punta Roca', region: 'La Libertad, El Salvador', blurb: "El Salvador's premier point break, a long, powerful right along a rocky headland.", lat: 13.4880, lon: -89.3220, offshoreDeg: 0 },
  picoalto: { name: 'Pico Alto', region: 'Punta Hermosa, Peru', blurb: "One of South America's premier big-wave reef breaks, south of Lima.", lat: -12.3330, lon: -76.8250, offshoreDeg: 90 },
  mancora: { name: 'Máncora', region: 'Piura, Peru', blurb: 'A long, warm-water left point in a lively northern Peru beach town.', lat: -4.1080, lon: -81.0480, offshoreDeg: 75 },
  guardadoembau: { name: 'Guarda do Embaú', region: 'Santa Catarina, Brazil', blurb: 'A river-mouth right point inside a protected coastal village.', lat: -27.9500, lon: -48.5830, offshoreDeg: 270 },
  itacare: { name: 'Itacaré', region: 'Bahia, Brazil', blurb: 'Jungle-backed beach breaks and points along a laid-back Bahia coastline.', lat: -14.2780, lon: -38.9960, offshoreDeg: 270 },
  rinconpr: { name: 'Rincón', region: 'Puerto Rico', blurb: "Puerto Rico's best-known surf town, with a string of reef and point breaks.", lat: 18.3400, lon: -67.2510, offshoreDeg: 90 },
  soupbowl: { name: 'Soup Bowl', region: 'Bathsheba, Barbados', blurb: "Barbados's premier wave, a punchy Atlantic-facing reef.", lat: 13.2170, lon: -59.5180, offshoreDeg: 270 },
  lasanta: { name: 'La Santa', region: 'Lanzarote, Canary Islands', blurb: 'A powerful, volcanic-reef left on a rugged, wind-exposed coast.', lat: 29.1330, lon: -13.7330, offshoreDeg: 165 },
  elconfital: { name: 'El Confital', region: 'Gran Canaria, Canary Islands', blurb: 'A long left point wrapping around a quiet stretch near Las Palmas.', lat: 28.1580, lon: -15.4460, offshoreDeg: 135 },
  supertubos: { name: 'Supertubos', region: 'Peniche, Portugal', blurb: 'A world-class, barreling beach break that hosts a stop on the world tour.', lat: 39.3490, lon: -9.3830, offshoreDeg: 90 },
  amado: { name: 'Praia do Amado', region: 'Algarve, Portugal', blurb: 'An exposed, reliable beach break near Sagres, a Euro surf-trip staple.', lat: 37.1810, lon: -8.9080, offshoreDeg: 90 },
  thursoeast: { name: 'Thurso East', region: 'Scotland, UK', blurb: 'A cold-water reef point that put Scottish surfing on the map.', lat: 58.5950, lon: -3.5140, offshoreDeg: 180 },
  bundoran: { name: 'Bundoran', region: 'Donegal, Ireland', blurb: "A cluster of reef and beach breaks along Ireland's rugged northwest.", lat: 54.4780, lon: -8.2830, offshoreDeg: 90 },
  lacanau: { name: 'Lacanau', region: 'France', blurb: 'A wide, exposed Atlantic beach break and French surf-culture hub.', lat: 44.9810, lon: -1.2030, offshoreDeg: 90 },
  anglet: { name: 'Anglet', region: 'France', blurb: "A string of jettied beach breaks next to Biarritz, France's surf capital.", lat: 43.4930, lon: -1.5280, offshoreDeg: 90 },
  dungeons: { name: 'Dungeons', region: 'Hout Bay, South Africa', blurb: 'A cold, shark-rich big-wave reef reserved for the heaviest South African swells.', lat: -34.0500, lon: 18.3460, offshoreDeg: 45 },
  elandsbay: { name: 'Elands Bay', region: 'Western Cape, South Africa', blurb: 'A long, cold-water left point on a remote stretch of West Coast.', lat: -32.3110, lon: 18.3330, offshoreDeg: 90 },
  padangpadang: { name: 'Padang Padang', region: 'Bali, Indonesia', blurb: 'A short, intense left barrel through a narrow reef slot.', lat: -8.8110, lon: 115.1050, offshoreDeg: 45 },
  keramas: { name: 'Keramas', region: 'Bali, Indonesia', blurb: 'A fast, punchy right reef break that hosts a world tour event.', lat: -8.5580, lon: 115.3480, offshoreDeg: 0 },
  lakeypeak: { name: 'Lakey Peak', region: 'Sumbawa, Indonesia', blurb: "A powerful A-frame reef peak, one of Sumbawa's best-known waves.", lat: -8.8830, lon: 118.5170, offshoreDeg: 0 },
  lagundribay: { name: 'Lagundri Bay', region: 'Nias, Indonesia', blurb: 'A long, hollow right point inside a horseshoe bay — one of the original Indonesian surf discoveries.', lat: 0.5580, lon: 97.7900, offshoreDeg: 0 },
  macaronis: { name: 'Macaronis', region: 'Mentawai Islands, Indonesia', blurb: 'A fun, rippable left reef widely rated among the most enjoyable waves on the planet.', lat: -2.7783, lon: 99.9842, offshoreDeg: 90 },
  bellsbeach: { name: 'Bells Beach', region: 'Victoria, Australia', blurb: 'A powerful, historic right point and home to the longest-running pro surf contest.', lat: -38.3690, lon: 144.2830, offshoreDeg: 0 },
  byronbay: { name: 'The Pass, Byron Bay', region: 'New South Wales, Australia', blurb: 'A long, easy right point wrapping around a lighthouse headland.', lat: -28.6350, lon: 153.6280, offshoreDeg: 250 },
  angourie: { name: 'Angourie', region: 'New South Wales, Australia', blurb: "A classic, sheltered right point — one of Australia's original dedicated surf reserves.", lat: -29.4700, lon: 153.3400, offshoreDeg: 270 },
  narrabeen: { name: 'North Narrabeen', region: 'Sydney, Australia', blurb: 'A punchy beach break off a rock shelf, a fixture of Sydney competitive surfing.', lat: -33.7180, lon: 151.3020, offshoreDeg: 270 },
  kirra: { name: 'Kirra', region: 'Gold Coast, Australia', blurb: 'Once one of the fastest, longest barrels on Earth off its groyne-fed sandbank.', lat: -28.1670, lon: 153.5330, offshoreDeg: 250 },
  piha: { name: 'Piha', region: 'Auckland, New Zealand', blurb: 'A wild, black-sand beach break beneath dramatic volcanic cliffs.', lat: -36.9530, lon: 174.4700, offshoreDeg: 90 },
  onjuku: { name: 'Onjuku', region: 'Chiba, Japan', blurb: "A consistent beach break close to Tokyo, popular with the city's surfers.", lat: 35.1170, lon: 140.3670, offshoreDeg: 270 },
  hikkaduwa: { name: 'Hikkaduwa', region: 'Sri Lanka', blurb: 'A mellow, reliable reef break inside a lively beach town.', lat: 6.1400, lon: 80.1000, offshoreDeg: 90 },
  weligama: { name: 'Weligama', region: 'Sri Lanka', blurb: "A wide, gentle bay that's become Sri Lanka's top spot to learn.", lat: 5.9730, lon: 80.4290, offshoreDeg: 0 },
  namotu: { name: 'Namotu Left', region: 'Mamanuca Islands, Fiji', blurb: 'A playful reef pass near Cloudbreak, friendlier but still a proper wave.', lat: -17.9330, lon: 177.2170, offshoreDeg: 45 },
  imsouane: { name: 'Imsouane', region: 'Morocco', blurb: "One of the world's longest right points, inside a working fishing bay.", lat: 30.8480, lon: -9.8180, offshoreDeg: 45 },
  tamarin: { name: 'Tamarin', region: 'Mauritius', blurb: 'A powerful left reef break known locally as "the Wall".', lat: -20.3260, lon: 57.3720, offshoreDeg: 90 },
  zarautz: { name: 'Zarautz', region: 'Basque Country, Spain', blurb: "One of Europe's longest beach breaks, a wide bay backed by green hills.", lat: 43.2830, lon: -2.1670, offshoreDeg: 180 },
  croyde: { name: 'Croyde', region: 'Devon, England', blurb: "A punchy, shallow beach break, one of England's best-loved waves.", lat: 51.1290, lon: -4.2350, offshoreDeg: 105 },
  unstad: { name: 'Unstad', region: 'Lofoten, Norway', blurb: 'A dramatic Arctic beach break framed by snow-capped peaks.', lat: 68.2830, lon: 13.0170, offshoreDeg: 90 },
  jungmun: { name: 'Jungmun', region: 'Jeju, South Korea', blurb: "South Korea's best-known beach break, on the island's south coast.", lat: 33.2440, lon: 126.4130, offshoreDeg: 0 },
  riyuebay: { name: 'Riyue Bay', region: 'Hainan, China', blurb: "China's most established surf spot, an exposed point on a resort coastline.", lat: 18.5480, lon: 110.2120, offshoreDeg: 270 },
  jinzun: { name: 'Jinzun', region: 'Taitung, Taiwan', blurb: "Taiwan's premier surf beach, host to an annual international contest.", lat: 22.9500, lon: 121.2350, offshoreDeg: 270 },
  pontadoouro: { name: 'Ponta do Ouro', region: 'Mozambique', blurb: 'An uncrowded point break just north of the South African border.', lat: -26.8500, lon: 32.8830, offshoreDeg: 270 },
  lennoxhead: { name: 'Lennox Head', region: 'New South Wales, Australia', blurb: 'A long, high-performance right point next to a dramatic headland.', lat: -28.7830, lon: 153.6000, offshoreDeg: 270 },

  // Third batch — added on a second "as many as you can" request, filling in regions the
  // first two batches left thin (US East Coast, Pacific Northwest, Ireland/UK, West Africa,
  // remote Australia, cold-water Atlantic). Same caveat as both earlier batches: reasonable
  // estimates from available sources, not surveyed. The remote/lesser-documented entries in
  // this batch (Todos Santos, Nihiwatu, Bawa, Wai'ao, Pasta Point, One Eye, Shipstern Bluff,
  // Sandvík, Lawrencetown, Cactus Beach) are lower-confidence than the rest -- built-in spots
  // known well enough to describe but without a precisely published coordinate double-checked.
  huntingtonbeach: { name: 'Huntington Beach', region: 'California, USA', blurb: '"Surf City USA" — long stretches of consistent, contest-friendly beach break peaks.', lat: 33.6553, lon: -118.0053, offshoreDeg: 45 },
  oceanbeachsf: { name: 'Ocean Beach', region: 'San Francisco, California, USA', blurb: 'Powerful, shifting beach break with strong currents and serious big-wave days.', lat: 37.7594, lon: -122.5107, offshoreDeg: 90 },
  swamis: { name: "Swami's", region: 'Encinitas, California, USA', blurb: 'A reliable, well-organized reef point popular with SoCal locals.', lat: 33.0281, lon: -117.2934, offshoreDeg: 60 },
  rockawaybeach: { name: 'Rockaway Beach', region: 'Queens, New York, USA', blurb: "New York City's home beach break, best in the fall and winter groundswell season.", lat: 40.5795, lon: -73.8351, offshoreDeg: 0 },
  capehatteras: { name: 'Cape Hatteras', region: 'Outer Banks, North Carolina, USA', blurb: 'Exposed Atlantic beach breaks that pick up nearly every hurricane swell.', lat: 35.2496, lon: -75.5284, offshoreDeg: 270 },
  follybeach: { name: 'Folly Beach', region: 'South Carolina, USA', blurb: "The Lowcountry's best-known beach break, a short drive from Charleston.", lat: 32.6551, lon: -79.9403, offshoreDeg: 315 },
  newsmyrnabeach: { name: 'New Smyrna Beach', region: 'Florida, USA', blurb: 'A consistent inlet beach break, notorious for its shark population.', lat: 29.0258, lon: -80.9270, offshoreDeg: 270 },
  peahi: { name: "Jaws (Pe'ahi)", region: 'Maui, Hawaii, USA', blurb: 'One of the biggest tow-in and paddle waves on Earth when a big NW swell hits.', lat: 20.9330, lon: -156.3140, offshoreDeg: 180 },
  alamoana: { name: 'Ala Moana Bowls', region: 'Oahu, Hawaii, USA', blurb: "A hollow, high-performance reef right just off Honolulu's south shore.", lat: 21.2830, lon: -157.8580, offshoreDeg: 0 },
  hanalei: { name: 'Hanalei Bay', region: 'Kauai, Hawaii, USA', blurb: 'A scenic, sheltered bay with gentle summer waves and a serious winter pier break.', lat: 22.2050, lon: -159.5000, offshoreDeg: 180 },
  shortsands: { name: 'Short Sands', region: 'Oregon, USA', blurb: 'A sheltered cove break in Oswald West State Park, a Pacific Northwest favorite.', lat: 45.7520, lon: -123.9700, offshoreDeg: 90 },
  westport: { name: 'Westport', region: 'Washington, USA', blurb: "A cold, powerful jetty break, one of the Pacific Northwest's most consistent spots.", lat: 46.9010, lon: -124.1450, offshoreDeg: 90 },
  todossantos: { name: 'Killers (Todos Santos)', region: 'Ensenada, Baja California, Mexico', blurb: 'A big-wave reef off an island, one of the heaviest waves in North America.', lat: 31.8300, lon: -116.7280, offshoreDeg: 90 },
  laticla: { name: 'La Ticla', region: 'Michoacán, Mexico', blurb: 'A long, hollow left point on a wild, largely undeveloped stretch of coast.', lat: 18.6060, lon: -103.6650, offshoreDeg: 45 },
  puntamita: { name: 'Punta Mita', region: 'Nayarit, Mexico', blurb: 'A gentle, long right point popular with longboarders in the Riviera Nayarit.', lat: 20.7730, lon: -105.5330, offshoreDeg: 90 },
  tamarindo: { name: 'Tamarindo', region: 'Guanacaste, Costa Rica', blurb: 'An easygoing beach and river-mouth break at the heart of a busy surf town.', lat: 10.2990, lon: -85.8370, offshoreDeg: 90 },
  dominical: { name: 'Dominical', region: 'Costa Rica', blurb: 'A powerful, punchy beach break on the jungle-backed southern Pacific coast.', lat: 9.2480, lon: -83.8620, offshoreDeg: 60 },
  venao: { name: 'Playa Venao', region: 'Panama', blurb: 'A crescent-shaped bay with consistent peaks on both ends, a backpacker surf hub.', lat: 7.4180, lon: -80.1980, offshoreDeg: 0 },
  playacolorado: { name: 'Playa Colorado', region: 'Nicaragua', blurb: 'A punchy, hollow right reef point popular with Central American surf camps.', lat: 11.7940, lon: -86.1940, offshoreDeg: 50 },
  cabarete: { name: 'Cabarete (Encuentro)', region: 'Dominican Republic', blurb: "The Caribbean's best-known surf town, with reefs and beach breaks for every level.", lat: 19.7580, lon: -70.4250, offshoreDeg: 180 },
  lawrencetown: { name: 'Lawrencetown Beach', region: 'Nova Scotia, Canada', blurb: "Atlantic Canada's best-known cold-water beach break.", lat: 44.6430, lon: -63.3860, offshoreDeg: 0 },
  pichilemu: { name: 'Pichilemu', region: 'Chile', blurb: "Chile's surf capital, with a long, rippable left point next to town.", lat: -34.3890, lon: -72.0010, offshoreDeg: 90 },
  arica: { name: 'El Gringo', region: 'Arica, Chile', blurb: "A powerful left point in Chile's far north, close to the Peruvian border.", lat: -18.4780, lon: -70.3210, offshoreDeg: 90 },
  montanita: { name: 'Montañita', region: 'Ecuador', blurb: "Ecuador's best-known surf town, with a lively beach and point break out front.", lat: -1.8330, lon: -80.7420, offshoreDeg: 90 },
  maresias: { name: 'Maresias', region: 'São Paulo, Brazil', blurb: "One of Brazil's best-known beach breaks, on a scenic bay near São Sebastião.", lat: -23.7960, lon: -45.5670, offshoreDeg: 10 },
  lapaloma: { name: 'La Paloma', region: 'Rocha, Uruguay', blurb: "Uruguay's low-key surf town, with reef and beach breaks scattered along the point.", lat: -34.6650, lon: -54.1500, offshoreDeg: 315 },
  watergatebay: { name: 'Watergate Bay', region: 'Cornwall, England', blurb: 'A wide, sandy Atlantic beach break popular with Cornish surf schools.', lat: 50.4420, lon: -5.0550, offshoreDeg: 135 },
  porthleven: { name: 'Porthleven', region: 'Cornwall, England', blurb: 'A shallow, powerful reef break beside a historic harbor wall.', lat: 50.0850, lon: -5.3160, offshoreDeg: 0 },
  rhossili: { name: 'Rhossili Bay', region: 'Gower, Wales', blurb: 'A dramatic three-mile beach break backed by cliffs and green hills.', lat: 51.5680, lon: -4.2930, offshoreDeg: 90 },
  lahinch: { name: 'Lahinch', region: 'County Clare, Ireland', blurb: "A consistent beach break beneath the Cliffs of Moher, Ireland's original surf town.", lat: 52.9330, lon: -9.3450, offshoreDeg: 90 },
  mullaghmore: { name: 'Mullaghmore Head', region: 'County Sligo, Ireland', blurb: 'A frigid, ferocious big-wave reef, among the heaviest waves in Europe.', lat: 54.4680, lon: -8.4470, offshoreDeg: 135 },
  biarritz: { name: 'Côte des Basques', region: 'Biarritz, France', blurb: 'A classic beach break beneath Biarritz, birthplace of European surfing.', lat: 43.4780, lon: -1.5660, offshoreDeg: 90 },
  somo: { name: 'Somo', region: 'Cantabria, Spain', blurb: 'A wide, sandy beach break across the bay from Santander.', lat: 43.4610, lon: -3.7440, offshoreDeg: 180 },
  carcavelos: { name: 'Carcavelos', region: 'Lisbon, Portugal', blurb: "Lisbon's most popular beach break, with a heavier reef at its northern end.", lat: 38.6800, lon: -9.3350, offshoreDeg: 30 },
  sandvik: { name: 'Sandvík', region: 'Reykjanes Peninsula, Iceland', blurb: 'A cold, moody beach break beneath volcanic cliffs, for the hardiest surfers.', lat: 63.8320, lon: -22.6980, offshoreDeg: 0 },
  hashpoint: { name: 'Hash Point', region: 'Taghazout, Morocco', blurb: 'A long right point in a laid-back fishing village turned surf destination.', lat: 30.5460, lon: -9.7100, offshoreDeg: 90 },
  ngor: { name: 'Ngor Right', region: 'Dakar, Senegal', blurb: "West Africa's best-known wave, a reef right off a small island village.", lat: 14.7460, lon: -17.5170, offshoreDeg: 90 },
  caverock: { name: 'Cave Rock', region: 'Durban, South Africa', blurb: "A punchy right reef at the entrance to Durban's harbor.", lat: -29.9130, lon: 31.0430, offshoreDeg: 270 },
  canggu: { name: 'Canggu (Batu Bolong)', region: 'Bali, Indonesia', blurb: "A lively reef break at the heart of Bali's surf-town scene.", lat: -8.6560, lon: 115.1330, offshoreDeg: 50 },
  nihiwatu: { name: "Nihiwatu (Occy's Left)", region: 'Sumba, Indonesia', blurb: 'A long, world-class left reef fronting a famous luxury resort.', lat: -9.6890, lon: 119.2870, offshoreDeg: 50 },
  bawa: { name: 'Bawa', region: 'Hinako Islands, Indonesia', blurb: 'A remote, near-perfect left barrel wrapping around a tiny island.', lat: 0.7500, lon: 97.1170, offshoreDeg: 50 },
  launion: { name: 'La Union', region: 'Philippines', blurb: "The Philippines' most popular surf town, with easygoing beach-break peaks.", lat: 16.6660, lon: 120.3130, offshoreDeg: 90 },
  miyazaki: { name: 'Kisakihama', region: 'Miyazaki, Japan', blurb: "One of Japan's best-known beach breaks, on the subtropical Kyushu coast.", lat: 31.9520, lon: 131.4590, offshoreDeg: 270 },
  midigama: { name: 'Midigama', region: 'Sri Lanka', blurb: 'A pair of reef breaks on the south coast, a step up from nearby Weligama.', lat: 5.9660, lon: 80.3960, offshoreDeg: 0 },
  waao: { name: "Wai'ao", region: 'Yilan, Taiwan', blurb: "Taiwan's most popular beach break, a short drive from Taipei.", lat: 24.8610, lon: 121.8580, offshoreDeg: 270 },
  pastapoint: { name: 'Pasta Point', region: 'Thulusdhoo, Maldives', blurb: 'A soft, playful left reef inside a resort-run atoll break.', lat: 4.3760, lon: 73.6440, offshoreDeg: 90 },
  oneeye: { name: 'One Eye', region: 'Le Morne, Mauritius', blurb: 'A world-class left reef breaking beneath a dramatic basalt mountain.', lat: -20.4560, lon: 57.3120, offshoreDeg: 90 },
  noosaheads: { name: 'Noosa Heads', region: 'Queensland, Australia', blurb: 'A string of gentle, scenic points inside a national park headland.', lat: -26.3980, lon: 153.0990, offshoreDeg: 225 },
  burleighheads: { name: 'Burleigh Heads', region: 'Gold Coast, Australia', blurb: 'A fast, sand-bottomed point next to a rocky headland, near the Superbank.', lat: -28.0930, lon: 153.4470, offshoreDeg: 250 },
  shipsternbluff: { name: 'Shipstern Bluff', region: 'Tasmania, Australia', blurb: 'A freakish, ledging slab beneath towering sea cliffs — as heavy as it looks.', lat: -43.1670, lon: 147.9330, offshoreDeg: 345 },
  thebox: { name: 'The Box', region: 'Gracetown, Western Australia', blurb: 'A short, ultra-heavy slab that breaks in shallow water close to the rocks.', lat: -33.8580, lon: 114.9980, offshoreDeg: 90 },
  cactus: { name: 'Cactus Beach', region: 'South Australia', blurb: 'A remote, wind-blasted cluster of world-class reefs on the Great Australian Bight.', lat: -32.0330, lon: 133.6330, offshoreDeg: 350 },
  restaurants: { name: 'Restaurants', region: 'Tavarua, Fiji', blurb: "Cloudbreak's playful neighbor, a lighter left reef inside the same reef pass.", lat: -17.8390, lon: 177.1890, offshoreDeg: 50 },
  shipwreckbay: { name: 'Shipwreck Bay', region: 'Ahipara, New Zealand', blurb: 'A long left point at the southern end of Ninety Mile Beach.', lat: -35.1670, lon: 173.1330, offshoreDeg: 90 },
};
export const ORDER = ['trestles', 'blacks', 'rincon', 'wedge', 'pipeline', 'teahupoo', 'jbay', 'uluwatu', 'snapper', 'nazare', 'chicama', 'raglan', 'puertoescondido', 'hossegor', 'mundaka', 'cloudbreak', 'skeletonbay', 'pavones', 'fistral', 'anchorpoint', 'margaretriver', 'montauk', 'arugambay', 'gland', 'siargao', 'ericeira', 'desertpoint', 'tofino', 'joaquina', 'puntadelobos', 'shonan', 'kovalam', 'caesarea', 'elcotillo', 'popoyo', 'santacatalina', 'deadmans', 'muine', 'laentrada', 'montoya', 'darne', 'capesolander', 'masnou', 'capomarina',
  'malibu', 'steamerlane', 'mavericks', 'waimeabay', 'sunsetbeach', 'honoluabay', 'hookipa', 'sayulita', 'barradelacruz', 'playahermosa', 'witchsrock', 'salsabrava', 'elsunzal', 'puntaroca', 'picoalto', 'mancora', 'guardadoembau', 'itacare', 'rinconpr', 'soupbowl', 'lasanta', 'elconfital', 'supertubos', 'amado', 'thursoeast', 'bundoran', 'lacanau', 'anglet', 'dungeons', 'elandsbay', 'padangpadang', 'keramas', 'lakeypeak', 'lagundribay', 'macaronis', 'bellsbeach', 'byronbay', 'angourie', 'narrabeen', 'kirra', 'piha', 'onjuku', 'hikkaduwa', 'weligama', 'namotu', 'imsouane', 'tamarin', 'zarautz', 'croyde', 'unstad', 'jungmun', 'riyuebay', 'jinzun', 'pontadoouro', 'lennoxhead',
  'huntingtonbeach', 'oceanbeachsf', 'swamis', 'rockawaybeach', 'capehatteras', 'follybeach', 'newsmyrnabeach', 'peahi', 'alamoana', 'hanalei', 'shortsands', 'westport', 'todossantos', 'laticla', 'puntamita', 'tamarindo', 'dominical', 'venao', 'playacolorado', 'cabarete', 'lawrencetown', 'pichilemu', 'arica', 'montanita', 'maresias', 'lapaloma', 'watergatebay', 'porthleven', 'rhossili', 'lahinch', 'mullaghmore', 'biarritz', 'somo', 'carcavelos', 'sandvik', 'hashpoint', 'ngor', 'caverock', 'canggu', 'nihiwatu', 'bawa', 'launion', 'miyazaki', 'midigama', 'waao', 'pastapoint', 'oneeye', 'noosaheads', 'burleighheads', 'shipsternbluff', 'thebox', 'cactus', 'restaurants', 'shipwreckbay'];
export const ONBOARDING_PICKS = ['trestles', 'pipeline', 'jbay', 'uluwatu', 'nazare', 'snapper', 'mundaka'];

export const HOUR_LABELS = ['5a', '7a', '9a', '11a', '1p', '3p', '5p', '7p'];
export const HOUR_INDICES = [5, 7, 9, 11, 13, 15, 17, 19];
export const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
