import { foldText, spotSearchText } from './placesearch.js';

// `swellWindow: [from, to]` is the compass arc (clockwise) a spot actually receives swell
// from, and `bestTide` is the tide it works best on ('low' | 'mid' | 'high' | 'all'). Both are
// optional: spots without them fall back to an arc derived from `offshoreDeg` — see
// lib/spotmodel.js, which explains why the derived arc is only a starting point and why the
// rule it replaced actively penalised the best waves in this list.
// The few spots the app can render before the catalog arrives.
//
// Copied verbatim from spots.catalog.js -- which is the whole 400-spot list, now loaded in its
// own chunk so the first render does not wait for 30KB of it (see loadCatalog below). These
// are the onboarding picks plus the default go-to spot, which between them cover every screen
// that can appear before the catalog lands.
//
// spots.test.js asserts these are byte-identical to their catalog entries, so the copy cannot
// quietly drift from the original.
export const SEED_SPOTS = {
  trestles: { name: 'Lower Trestles', region: 'San Clemente, CA', blurb: 'Cobblestone point wrapping into long, workable walls. Best before the wind fills in.', lat: 33.3825, lon: -117.5972, offshoreDeg: 60, swellWindow: [180, 230], bestTide: 'mid' },
  pipeline: { name: 'Pipeline', region: 'Oahu, Hawaii', blurb: "World-famous reef barrel on the North Shore. Heavy, shallow, and unforgiving when it's on.", lat: 21.6647, lon: -158.0538, offshoreDeg: 200, swellWindow: [290, 350], bestTide: 'mid' },
  jbay: { name: 'Jeffreys Bay', region: 'Eastern Cape, South Africa', blurb: 'Long, high-speed right point — one of the best walls in the world when it lines up.', lat: -34.0489, lon: 24.9087, offshoreDeg: 325, swellWindow: [190, 240], bestTide: 'all' },
  uluwatu: { name: 'Uluwatu', region: 'Bali, Indonesia', blurb: "Dramatic reef break beneath a clifftop temple, with several sections down the point.", lat: -8.8290, lon: 115.0870, offshoreDeg: 50, swellWindow: [200, 250], bestTide: 'mid' },
  nazare: { name: 'Nazaré', region: 'Portugal', blurb: 'Home to some of the biggest waves ever surfed, thanks to an underwater canyon offshore.', lat: 39.6033, lon: -9.0705, offshoreDeg: 85, swellWindow: [280, 330], bestTide: 'all' },
  snapper: { name: 'Snapper Rocks', region: 'Gold Coast, Australia', blurb: 'The Superbank — impossibly long, fast right points when the sand banks line up.', lat: -28.1590, lon: 153.5470, offshoreDeg: 250, swellWindow: [100, 160], bestTide: 'all' },
  mundaka: { name: 'Mundaka', region: 'Basque Country, Spain', blurb: 'A world-class left river-mouth wave that peels around a sandbar.', lat: 43.4070, lon: -2.6990, offshoreDeg: 180, swellWindow: [300, 340], bestTide: 'mid' },
};

// The whole catalog, fetched on demand. Vite gives this its own chunk because the import is
// dynamic, so it downloads alongside the app rather than inside it, and caches separately.
let catalogPromise = null;
export function loadCatalog() {
  // Memoised: several views ask for this independently and none of them should trigger a
  // second fetch or a second parse of a 400-entry object.
  if (!catalogPromise) {
    catalogPromise = import('./spots.catalog.js')
      .then((m) => m.CATALOG)
      .catch((e) => { catalogPromise = null; throw e; }); // let a failed load be retried
  }
  return catalogPromise;
}
export const ORDER = [
  'trestles', 'blacks', 'rincon', 'wedge', 'pipeline', 'teahupoo', 'jbay', 'uluwatu', 'snapper', 'nazare',
  'chicama', 'raglan', 'puertoescondido', 'hossegor', 'mundaka', 'cloudbreak', 'skeletonbay', 'pavones',
  'fistral', 'anchorpoint', 'margaretriver', 'montauk', 'arugambay', 'gland', 'siargao', 'ericeira',
  'desertpoint', 'tofino', 'joaquina', 'puntadelobos', 'shonan', 'kovalam', 'caesarea', 'elcotillo', 'popoyo',
  'santacatalina', 'deadmans', 'muine', 'laentrada', 'montoya', 'darne', 'capesolander', 'masnou',
  'capomarina', 'malibu', 'steamerlane', 'mavericks', 'waimeabay', 'sunsetbeach', 'honoluabay', 'hookipa',
  'sayulita', 'barradelacruz', 'playahermosa', 'witchsrock', 'salsabrava', 'elsunzal', 'puntaroca', 'picoalto',
  'mancora', 'guardadoembau', 'itacare', 'rinconpr', 'soupbowl', 'lasanta', 'elconfital', 'supertubos',
  'amado', 'thursoeast', 'bundoran', 'lacanau', 'anglet', 'dungeons', 'elandsbay', 'padangpadang', 'keramas',
  'lakeypeak', 'lagundribay', 'macaronis', 'bellsbeach', 'byronbay', 'angourie', 'narrabeen', 'kirra', 'piha',
  'onjuku', 'hikkaduwa', 'weligama', 'namotu', 'imsouane', 'tamarin', 'zarautz', 'croyde', 'unstad', 'jungmun',
  'riyuebay', 'jinzun', 'pontadoouro', 'lennoxhead', 'huntingtonbeach', 'oceanbeachsf', 'swamis',
  'rockawaybeach', 'capehatteras', 'follybeach', 'newsmyrnabeach', 'alamoana', 'hanalei', 'shortsands',
  'westport', 'todossantos', 'laticla', 'puntamita', 'tamarindo', 'dominical', 'venao', 'playacolorado',
  'cabarete', 'lawrencetown', 'pichilemu', 'arica', 'montanita', 'maresias', 'lapaloma', 'watergatebay',
  'porthleven', 'rhossili', 'lahinch', 'mullaghmore', 'biarritz', 'somo', 'carcavelos', 'sandvik', 'hashpoint',
  'ngor', 'caverock', 'canggu', 'nihiwatu', 'bawa', 'launion', 'miyazaki', 'midigama', 'waao', 'pastapoint',
  'oneeye', 'noosaheads', 'burleighheads', 'shipsternbluff', 'thebox', 'cactus', 'restaurants', 'shipwreckbay',
  'sunsetcliffs', 'sanonofre', 'cardiffreef', 'oceansidepier', 'venturapoint', 'countyline', 'pleasurepoint',
  'lindamar', 'windansea', 'elporto', 'zuma', 'sebastianinlet', 'cocoabeach', 'wrightsville', 'virginiabeach',
  'longbeachny', 'narragansett', 'manasquan', 'jaws', 'rockypoint', 'queens', 'makaha', 'scorpionbay',
  'sanmiguel', 'troncones', 'elzonte', 'lasflores', 'olliespoint', 'nosara', 'bocasbluff', 'lobitos',
  'iquique', 'matanzas', 'saquarema', 'noronha', 'praiadorosa', 'guincho', 'sagres', 'pantin', 'rodiles',
  'capbreton', 'easkey', 'porthcawl', 'saltburn', 'scheveningen', 'sylt', 'klitmoller', 'hoddevik',
  'killerpoint', 'safi', 'dakhla', 'sealpoint', 'muizenberg', 'newpier', 'tofo', 'hiltonbeach', 'hollowtrees',
  'bingin', 'medewi', 'tland', 'krui', 'kata', 'ikumi', 'baler', 'chickens', 'winkipop', 'crescenthead',
  'duranbah', 'maroubra', 'bondi', 'manly', 'gnaraloo', 'redbluff', 'yallingup', 'stclair', 'makorori',
  'fitzroybeach', 'nahariya', 'akko', 'batgalim', 'atlit', 'habonim', 'nahsholim', 'beithanania', 'michmoret',
  'beityanai', 'sironit', 'poleg', 'herzliya', 'maravi', 'bananabeach', 'batyam', 'palmachim', 'ashdod',
  'ashkelon', 'mardelplata', 'necochea', 'miramar', 'puntadeleste', 'itamambuca', 'imbituba', 'buchupureo',
  'curanipe', 'caboblanco', 'pacasmayo', 'puntarocas', 'ayampe', 'elparedon', 'maderas', 'lasaladita',
  'puntaconejo', 'bostonbay', 'playagrande', 'gaschambers', 'freightsbay', 'mountirvine', 'ribeiragrande',
  'jardimdomar', 'pontapreta', 'yoff', 'busua', 'robertsport', 'burehbeach', 'caboledo', 'diani', 'batroun',
  'curium', 'levanto', 'santamarinella', 'machrihanish', 'peasebay', 'thorlakshofn', 'toro', 'oostende',
  'coxos', 'praiagrande', 'razo', 'menakoz', 'lafitenia', 'mulki', 'manapad', 'sultans', 'cherating', 'mykhe',
  'calicoan', 'fulong', 'kamogawa', 'songjeong', 'haatafu', 'salani', 'pangopoint', 'ouano', 'vanimo', 'ppass',
  'boatbasin', 'bawleypoint', 'werribeach', 'scarboroughwa', 'whangamata', 'mountmaunganui', 'sombrio',
  'saltcreek', 'pacificbeach', 'oceancitymd', 'kommetjie', 'llandudno', 'scarboroughct', 'bigbay',
  'victoriabay', 'outerpool', 'buffalobay', 'wilderness', 'lookoutbeach', 'brucesbeauties', 'pipepe',
  'nahoonreef', 'mdumbi', 'coffeebay', 'scottburgh', 'stmichaels', 'umhlanga', 'alkantstrand', 'swakopmund',
  'langstrand', 'baiaazul', 'palmeirinhas', 'pontamalongane', 'zavora', 'macaneta', 'lavanono', 'anakao',
  'libanona', 'saintleu', 'boucancanot', 'troisbassins', 'termales', 'palomino', 'playaelagua', 'playabaracoa',
  'surfersbeach', 'tartane', 'lemoule', 'kalonero', 'falasarna', 'sile', 'kilyos', 'chalupy', 'tjornuvik',
  'asparuhovo', 'gonio', 'ghajntuffieha', 'bizerte', 'zeralda', 'agami', 'mughsayl', 'masirah', 'ramin',
  'hawkesbay', 'coxsbazar', 'ngwesaung', 'varkala', 'serenitybeach', 'ummsuqeim', 'nouakchott', 'kotupoint',
  'assinie', 'tarkwabay', 'kribi', 'santana', 'mayumba', 'pointenoire', 'paje', 'anseintendance',
  'khalaktyrsky', 'backbeach', 'titiana', 'avanapassage', 'tsurigasaki', 'shimoda', 'habushiura', 'houhai',
  'jukdo', 'cannonbeach', 'pascuales', 'nexpa', 'horseshoebay', 'elpalmar', 'cabedelo', 'latorche',
  'capomannu', 'impossibles', 'balangan', 'dreamland', 'nusadua', 'serangan', 'sanurreef', 'greenbowl',
  'echobeach', 'batukaras', 'cimaja', 'onepalmpoint', 'gerupuk', 'mawi', 'ekas', 'supersuck', 'periscopes',
  'lancesleft', 'telescopes', 'puraran', 'liwliwa', 'lanuza', 'whiskeypoint', 'peanutfarm', 'kabalana',
  'torami', 'niijima', 'offthewall', 'logcabins', 'laniakea', 'chunsreef', 'haleiwa', 'velzyland',
  'diamondhead', 'sandybeach', 'kewalos', 'poipu', 'tunnelskauai', 'maalaea', 'avalonbeach', 'deewhy',
  'cronulla', 'merewether', 'sandonpoint', 'sealrocks', 'yamba', 'scottshead', 'currumbin', 'cylinders',
  'agneswater', 'torquaypoint', 'thirteenthbeach', 'gunnamatta', 'woolamai', 'johanna',
  'cliftonbeach', 'marrawah', 'middletonsa', 'northpointwa', 'threebears', 'injidup', 'jakespoint', 'lancelin',
  'manubay', 'muriwai', 'wainui', 'taylorsmistake', 'wilkespass', 'frigatespassage', 'papara', 'taapuna',
  'haapiti', 'coconutssamoa', 'baleal', 'ribeiradilhas', 'arrifana', 'bordeira', 'costadacaparica', 'espinho',
  'figueiradafoz', 'zurriola', 'sopelana', 'bakio', 'salinas', 'loslocos', 'elquemao', 'laizquierda',
  'guethary', 'seignosse', 'biscarrosse', 'vieuxboucau', 'lapalue', 'woolacombe', 'bantham', 'aileens',
  'strandhill', 'inchbeach', 'tramore', 'lapunta', 'zippers', 'monumentscabo', 'k38', 'chacahua', 'matanchen',
  'playanegracr', 'avellanas', 'santateresa', 'bocabarranca', 'esterillos', 'manzanillonic', 'pangadrops',
  'mizata', 'k59', 'playateta', 'huanchaco', 'cerroazul', 'laherradura', 'renaca', 'puntadetralca', 'arpoador',
  'barratijuca', 'prainharj', 'mole', 'nagshead', 'jacksonvillebeach', 'melbournebeach', 'gilgobeach',
  'ruggles', 'nauset', 'higginsbeach', 'pismobeach', 'morrobay', 'jalama', 'doheny', 'boilers', 'bananapoint',
  'tamri', 'trespalmas', 'domespr',
  'pacificcity', 'otterrock', 'agatebeach', 'seasideor', 'bastendorff', 'lapush', 'hobuck', 'longbeachwa',
  'kugenuma', 'yuigahama', 'hebara', 'choshi', 'oarai', 'omaezaki', 'kaifu', 'hyuga',
  'aoshima', 'tanegashima', 'sennen', 'perranporth', 'polzeath', 'bude', 'constantinebay', 'freshwaterwest',
  'llangennith', 'tynemouth', 'scarborough', 'garrettstown', 'rossnowlagh', 'lyallbay', 'papamoa', 'ohope',
  'kaikoura', 'newbrighton', 'coxbay', 'chesterman', 'martiniquens', 'mahabalipuram', 'gokarna', 'puri',
  'borestranden', 'vikiceland', 'topocalma', 'concon', 'rehoboth', 'assateague', 'tybee',
  'southpadre', 'galveston', 'pensacola', 'hamptonnh', 'longsandsme',
  'grumari', 'recreio', 'macumba', 'silveira', 'ferrugem', 'campeche', 'barradalagoa', 'santinho', 'geriba', 'pipabr',
  'baiaformosa', 'praiadofuturo', 'tombo', 'camburi', 'tuason', 'pacifico', 'charliespoint', 'crystalbeach', 'bagasbas', 'borongan',
  'dahican', 'realquezon', 'shipwrecksnl', 'playgrounds', 'scarreef', 'maluk', 'sawarna', 'kutabeach', 'airportlefts', 'balian',
  'tanjungaan', 'brimsness', 'sandside', 'fraserburgh', 'coldingham', 'belhaven', 'tiree', 'dalmore', 'scarista', 'waitpinga',
  'goolwa', 'boomerbeach', 'moana', 'southportsa', 'blackfellows', 'dalyhead', 'pondalowie', 'playagrandecr', 'malpais', 'jaco',
  'cocles', 'matapalo', 'marbellacr', 'abreojos', 'sancarlosbaja', 'cerritos', 'shipwreckscabo', 'caletadecampos', 'zipolite', 'sanbartolo',
  'losorganos', 'elnuro', 'puntasal', 'makahalima', 'maitencillo', 'ritoque', 'llico', 'cobquecura', 'laserena', 'canoa',
  'salinasec', 'mompiche', 'gigante', 'remanso', 'hermosasjds', 'silverbacks', 'riomar', 'jailbreaks', 'lohis', 'natadola',
  'swimmingpools', 'marias', 'jobos', 'crashboat', 'macao', 'playabonita', 'surferspoint', 'varazze', 'dulan', 'jialeshui',
  'gyeongpo', 'jinha', 'nonnuoc', 'islalobos', 'lascanteras', 'elmedano', 'socorro', 'sidikaouki', 'essaouira', 'lasource',
  'kallialay', 'sasihithlu', 'hiriketiya', 'madiha', 'kujukuri', 'amami', 'irino', 'ansteys', 'noordhoek', 'saopedrodemoel',
  'vagueira', 'zambujeira', 'lizandro', 'berria', 'patos', 'mimizan', 'capferret', 'siouville', 'crabisland', 'keelachill',
  'portrush', 'manorbier', 'hellsmouth', 'kimmeridge', 'ervik', 'lokken',
  'pinamar', 'villagesell', 'joseignacio', 'labarra', 'orre', 'grindavik', 'vorupor', 'agger',
  'rabodepeixe', 'vaanajoesuu', 'yyteri', 'stouensbay',
  'honolii', 'banyans', 'pinetrees', 'waipio', 'lahainaharbor', 'pakala', 'topanga', 'lunadabay',
  'hermosa', 'blackies', 'brooksstreet', 'tstreet', 'obsd', 'imperialbeach', 'elcapitan', 'leadbetter',
  'bolinas', 'sanddollar', 'belmar', 'lbi', 'rodanthe', 'reefroad', 'bobhall', 'matunuck',
  'hullbay', 'olasaltas', 'petacalco', 'sanpedrito', 'barradenavidad', 'revolcadero', 'cambutal', 'sipacate',
  'bullbay', 'sanssouci', 'applebay', 'longbeachbc', 'jordanriver', 'cowbay', 'itacoatiara', 'regencia',
  'maracaipe', 'praiadofrances', 'torres', 'matinhos', 'paracuru', 'praiabrava', 'hangaroa', 'chapadmalal',
  'puntacarola', 'totoralillo', 'lasauzaie', 'hendaye', 'moliets', 'montalivet', 'quiberon', 'buggerru',
  'portoferro', 'famara', 'tapia', 'liencres', 'doninos', 'matosinhos', 'gwithian', 'saunton',
  'llantwit', 'enniscrone', 'wijkaanzee', 'mehdia', 'darbouazza', 'mirleft', 'sidiifni', 'kalkbay',
  'glenbeach', 'ballito', 'ouakam', 'kokrobite', 'cabarita', 'coolum', 'freshwater', 'avoca',
  'lorne', 'trigg', 'strickland', 'stentroad', 'castlepoint', 'porpoisebay', 'lhoknga', 'watukarung',
  'selongbelanak', 'sunabe', 'itoshima', 'pagudpud', 'arambol', 'fare', 'kabic', 'brandonbay',
  'nusalefts', 'indianbeach', 'brokenhead', 'shimeibay',
  'santacruzpt', 'monteclerigo', 'castelejo', 'beliche', 'povoa', 'cabedeloviana', 'praiadabarra', 'mira',
  'portodacruz', 'xago', 'canosdemeca', 'langre', 'deba', 'alanzada', 'nemina', 'elfronton',
  'almaciga', 'contis', 'carcans', 'leporge', 'soulac', 'vertbois', 'sablesdolonne', 'guidel',
  'ostia', 'viareggio', 'porthtowan', 'praasands', 'caytonbay', 'newgale', 'farrbay', 'kilkee',
  'ballybunion', 'magheroarty', 'warnemunde', 'domburg', 'rabat', 'oualidia', 'devilsrock', 'sanpancho',
  'chacala', 'tourmaline', 'beacons', 'tamarack', 'sealbeach', 'venicebreakwater', 'campuspoint', 'carmel',
  'naturalbridges', 'montara', 'asburypark', 'oceancitynj', 'jupiter', 'pointjudith', 'goodharbor', 'makapuu',
  'kahaluu', 'launiupoko', 'pinegrove', 'wildernesspr', 'southpoint', 'playalangosta', 'arraial', 'stellamaris',
  'juquehy', 'ilhadomel', 'tramandai', 'matadeiro', 'puntadeldiablo', 'lapedrera', 'portstjohns', 'cintsa',
  'saintpierre', 'capethreepoints', 'moffat', 'alexheadland', 'redhead', 'terrigal', 'palmbeach', 'bombo',
  'mollymook', 'janjuc', 'pointleo', 'cottesloe', 'eaglehawkneck', 'sandybaynz', 'mangawhai', 'tairua',
  'waihi', 'taurangabay', 'nyangnyang', 'pulaumerah', 'nakatajima', 'kokufu', 'nanwan', 'woljeong',
  'mirissa', 'covelong', 'northwollongong', 'pottuvil',
  'lajollashores', 'delmar', 'moonlight', 'ponto', 'fiftyfourth', 'aliso', 'manhattanbeach', 'mondos',
  'hammonds', 'refugio', 'cayucos', 'asilomar', 'manresa', 'waddell', 'stinson', 'salmoncreek',
  'moonstone', 'florencejetty', 'lincolncity', 'satellitebeach', 'flagler', 'staugustine', 'carolinabeach', 'isleofpalms',
  'sandbridge', 'seasideheights', 'jenness', 'ogunquit', 'yokohama', 'bellows', 'kalapaki', 'bigbeach',
  'cuyutlan', 'burros', 'puntamango', 'monterrico', 'aviones', 'mollendo', 'pimentel', 'zorritos',
  'puertecillo', 'constitucion', 'antofagasta', 'engabao', 'praiadoforte', 'cassino', 'jericoacoara', 'pontanegra',
  'areiabranca', 'magoito', 'almograve', 'odeceixe', 'meron', 'sanlorenzo', 'laga', 'majanicho',
  'hourtin', 'labenne', 'bidart', 'widemouth', 'westwardho', 'boscombe', 'whitby', 'aberavon',
  'whitesands', 'sandend', 'spanishpoint', 'doughmore', 'fanore', 'castlerock', 'zandvoort', 'apelviken',
  'bouznika', 'plagedesnations', 'heroldsbay', 'melkbos', 'stilbaai', 'etangsale', 'saintgilles', 'doubleisland',
  'coffs', 'portmacquarie', 'forster', 'treachery', 'nobbys', 'thefarm', 'smithsbeach', 'kilcunda',
  'portcampbell', 'logans', 'tearai', 'mangamaunu', 'hiratsuka', 'shirahama', 'haeundae', 'donghe',
  'khaolak', 'kalim', 'juara', 'talofofo',
  'cottons', 'hbcliffs', 'bolsachica', 'redondo', 'oceansideharbor', 'seasidereef', 'terramar', 'poche',
  'capitola', 'montanadeoro', 'fortpoint', 'dillon', 'manzanita', 'goldbeach', 'oceanshores', 'jonesbeach',
  'topsail', 'myrtle', 'daytona', 'vero', 'fortpierce', 'juno', 'boynton', 'surfsidetx',
  'portaransas', 'mokuleia', 'kealia', 'polihale', 'kuabay', 'mazunte', 'ostional', 'jiquilillo',
  'lapared', 'middlecove', 'bombinhas', 'moledo', 'ofir', 'furadouro', 'tocha', 'pedrogao',
  'fozdoarelho', 'malhao', 'monteverde', 'verdicio', 'vega', 'itzurun', 'baldaio', 'petitbec',
  'stgilles', 'saintebarbe', 'portreath', 'lynmouth', 'eastwittering', 'jossbay', 'cromer', 'aberdeen',
  'sandwood', 'carrowniskey', 'coumeenoole', 'rossbeigh', 'bunmahon', 'inchydoney', 'hanstholm', 'aglou',
  'legzira', 'portalfred', 'naturesvalley', 'kogelbay', 'gonubie', 'ajigaura', 'kitaizumi', 'isonoura',
  'okuragahama', 'dadaepo', 'honeymoonbay', 'xichong', 'bigwavebay', 'vungtau', 'kedungu', 'culburra',
  'tathra', 'thirroul', 'nambucca', 'evanshead', 'peregian', 'thespit', 'portsea', 'pointaddis',
  'anglesea', 'fairhaven', 'ellensbrook', 'baylys', 'karioitahi', 'opunake', 'oakura', 'cobden',
  'hideaway', 'rochepercee', 'staithes', 'standrews',
  'scripps', 'coronado', 'crystalcove', 'santamonica', 'elsegundo', 'tarpits', 'pitas', 'devereux',
  'surfbeach', 'garrapata', 'mosslanding', 'davenport', 'pointarena', 'bandon', 'brigantine', 'atlanticcity',
  'capemay', 'indianriver', 'emeraldisle', 'ocracoke', 'playalinda', 'panamacity', 'wellsbeach', 'popham',
  'tracks', 'kiheicove', 'anahola', 'pohoiki', 'bajamalibu', 'lapastora', 'piedelacuesta', 'carrizalillo',
  'eltunco', 'samara', 'manuelantonio', 'islagrande', 'brandons', 'leblon', 'saoconrado', 'itaipuacu',
  'morrodaspedras', 'puntamogotes', 'iloca', 'zavial', 'agucadoura', 'quiaios', 'madalena', 'frouxeira',
  'roche', 'karraspio', 'truevert', 'saintgirons', 'tarnos', 'mawganporth', 'porthmeor', 'kennack',
  'wembury', 'compton', 'harlyn', 'trebarwith', 'melvich', 'pollanbay', 'barleycove', 'brusand',
  'noordwijk', 'moulaybouzerktoun', 'tafedna', 'greenpointkzn', 'margatekzn', 'taito', 'shizunami', 'kashima',
  'areguling', 'fingal', 'kingscliff', 'tallows', 'ballina', 'emeraldbeach', 'sawtell', 'hathead',
  'cavesbeach', 'monavale', 'garie', 'broulee', 'pointlonsdale', 'oceangrove', 'flinders', 'capepaterson',
  'bunbury', 'gnarabup', 'denmarkwa', 'secretharbour', 'pakiri', 'bethells', 'karekare', 'hotwater',
  'waimarama', 'castlecliff', 'colacbay', 'pointplomer',
  'musselshoals', 'pointmugu', 'oxnardshores', 'cabrillo', 'loverspoint', 'sunsetstate', 'gualala', 'winchesterbay',
  'portorford', 'harrisbeach', 'corolla', 'pawleys', 'huntingisland', 'amelia', 'mayport', 'navarre',
  'gulfshores', 'cisco', 'misquamicut', 'kennebunk', 'oldorchard', 'reidstate', 'kailua', 'hapuna',
  'majorsbay', 'ukumehame', 'kalihiwai', 'whitepoint', 'maruata', 'elpalmarixtapa', 'elpalmarcito', 'shacks',
  'canegarden', 'puertocolombia', 'elvalle', 'lebu', 'bucalemu', 'itapua', 'capaodacanoa', 'bonete',
  'barradosahy', 'saopedroestoril', 'afife', 'macas', 'noja', 'laredo', 'lasalie', 'capdelhomy',
  'latranche', 'langland', 'dunnetbay', 'lunanbay', 'beadnell', 'hvidesande', 'molle', 'norderney',
  'chia', 'fregene', 'aindiab', 'paradisebeach', 'umzumbe', 'wolpo', 'baishawan', 'shilaoren',
  'littleandaman', 'ashwem', 'okanda', 'hachijojima', 'desaru', 'broomshead', 'southwestrocks', 'lakecathie',
  'crowdyhead', 'boomerang', 'hawksnest', 'birubi', 'soldiers', 'theentrance', 'stanwellpark', 'narooma',
  'mermaid', 'pointcartwright', 'rainbowbeach', 'inverloch', 'apollobay', 'portfairy', 'lakesentrance', 'robe',
  'petrelcove', 'pennington', 'redgate', 'esperance', 'parkbeachtas', 'ruakaka', 'aramoana', 'tolagabay',
  'blackhead', 'midway', 'papenoo', 'sevenmile',
  'torreypines', 'missionbeach', 'silverstrandsd', 'hbstate', 'playadelrey', 'hollywoodbeach', 'santaclaus', 'avila',
  'oceano', 'sansimeon', 'andrewmolera', 'seacliff', 'pescadero', 'crescentcity', 'yachats', 'kalaloch',
  'ormond', 'canaveral', 'lakeworth', 'delray', 'deerfield', 'pompano', 'haulover', 'pontevedra',
  'destin', 'oakisland', 'surfcity', 'duck', 'springlake', 'longbranch', 'robertmoses', 'secondbeach',
  'marconi', 'plumisland', 'wallissands', 'waimanalo', 'ewabeach', 'hamoa', 'richardsons', 'florenciabay',
  'cerritosmaz', 'puntabaja', 'rosalillita', 'astillero', 'iztapa', 'portlouis', 'mehuin', 'tongoy',
  'guarapari', 'serragrande', 'guaratiba', 'montehermoso', 'ancora', 'portocovo', 'milfontes', 'orinon',
  'gorliz', 'traba', 'frexulfe', 'ondres', 'erdeven', 'penhors', 'blancssablons', 'hatainville',
  'hayling', 'filey', 'crackington', 'rhosneigr', 'barvas', 'skaill', 'streedagh', 'dunmoran',
  'flakstad', 'marinadipisa', 'anza', 'yzerfontein', 'sedgefield', 'kenton', 'niyodo', 'iluka',
  'woolgoolga', 'lighthousebeach', 'oldbar', 'fingalbay', 'catherinehill', 'wamberal', 'macmasters', 'windang',
  'tuross', 'merimbula', 'venusbay', 'wedgeisland', 'waipucove', 'omaha', 'whiritoa', 'kumarapatch',
  'gorebay', 'brightonnz', 'aganoa', 'titahi',
  'buccaneer', 'crescentbay', 'pointdume', 'gaviota', 'fourmile', 'scottcreek', 'poplar', 'jenner',
  'sheltercove', 'humboldtjetty', 'neskowin', 'newportjetty', 'capelookout', 'kodiak', 'kaisers', 'chinawalls',
  'makua', 'laiepoint', 'windmills', 'olowalu', 'hideaways', 'kekaha', 'breneckes', 'kolekole',
  'pololu', 'moomomi', 'kepuhi', 'turtlecove', 'southampton', 'westhampton', 'smithpoint', 'pointlookout',
  'sandyhook', 'dealnj', 'seagirt', 'pointpleasant', 'lavallette', 'islandbeach', 'holgate', 'ventnor',
  'seaisle', 'wildwood', 'capehenlopen', 'bethany', 'kittyhawk', 'oregoninlet', 'avon', 'frisco',
  'atlanticbeachnc', 'kurebeach', 'gardencity', 'hiltonhead', 'vilano', 'crescentbeachfl', 'matanzasfl', 'ponceinlet',
  'indialantic', 'jensen', 'bocainlet', 'southbeachmiami', 'salisbury', 'fortunesrocks', 'matagorda', 'crystalbeachtx',
  'middles', 'montones', 'surfersbeachpr', 'dorado', 'canebay', 'sanquintin', 'santotomas', 'elsocorro',
  'bahiaasuncion', 'migrino', 'ninepalms', 'playabrujas', 'elborrego', 'lodemarcos', 'quimixto', 'eltecuan',
  'melaque', 'elparaisocolima', 'farobucerias', 'playaazul', 'laspenas', 'playalindaixtapa', 'barradepotosi', 'barravieja',
  'colotepec', 'sanagustinillo', 'chipehua', 'puertoarista', 'champerico', 'labocanasv', 'loscobanos', 'barrasantiago',
  'elcuco', 'playaamarillo', 'playamarsella', 'playayankee', 'eltransito', 'aserradores', 'masachapa', 'pochomil',
  'junquillal', 'sanjuanillo', 'playapelada', 'buenavistacr', 'camaronal', 'playacoyote', 'tivives', 'rocaloca',
  'bejuco', 'paloseco', 'dominicalito', 'puntabanco', 'morronegrito', 'destiladeros', 'paunch', 'redfrog',
  'guanabo', 'parlour', 'duppies', 'maycocks', 'grandriviere', 'toco', 'balandra', 'pigeonpoint',
  'ansebonneville', 'bassepointe', 'ansebertrand', 'lehelleux', 'lorient', 'josiahs', 'costeno', 'olon',
  'sanmateo', 'playasec', 'puntacarnero', 'loberia', 'sua', 'puemape', 'senoritas', 'chilca',
  'vichayito', 'huayquique', 'pichicuy', 'algarrobo', 'cahuil', 'pelluhue', 'cucao', 'cidreira',
  'pinheira', 'lagoinhadoleste', 'mocambique', 'ingleses', 'enseadasfs', 'guaratuba', 'peruibe', 'pauba',
  'barradouna', 'vermelhanorte', 'felix', 'lopesmendes', 'leme', 'jacone', 'tucuns', 'farolsaotome',
  'praiadacosta', 'itaunas', 'tiririca', 'engenhoca', 'praiadofortebahia', 'arembepe', 'trancoso', 'barrasaomiguel',
  'coqueirinho', 'baiadatraicao', 'pirangi', 'taiba', 'cabopolonio', 'manantiales', 'santaclaradelmar', 'carilo',
  'claromeco', 'leca', 'lavadores', 'miramargaia', 'granja', 'cortegaca', 'torreira', 'costanova',
  'vieira', 'paredesvitoria', 'consolacao', 'praiaazul', 'adraga', 'fontedatelha', 'meco', 'salema',
  'valefigueiras', 'portomoniz', 'seixal', 'saovicente', 'mosteiros', 'orio', 'loredo', 'tagle',
  'oyambre', 'andrin', 'sanantolin', 'quebrantos', 'otur', 'penarronda', 'sanxurxo', 'carnota',
  'montalvo', 'aguarda', 'conil', 'zahara', 'caletacaballo', 'rockypointfv', 'esquinzo', 'flagbeach',
  'laparedfv', 'puntablanca', 'bajamar', 'erromardie', 'ilbarritz', 'cavaliers', 'messanges', 'estagnots',
  'lespecier', 'grandcrohot', 'legurp', 'cotiniere', 'lacoubre', 'notredamedemonts', 'longeville', 'fortbloque',
  'tronoen', 'trezgoarem', 'trepasses', 'lostmarch', 'dossen', 'minou', 'surtainville', 'wimereux',
  'gwenver', 'polurrian', 'chapelporth', 'trevaunance', 'holywell', 'crantock', 'porthcothan', 'sandymouth',
  'putsborough', 'challaborough', 'thurlestone', 'brighton', 'walcott', 'redcar', 'druridge', 'bamburgh',
  'caswell', 'broadhaven', 'ogmore', 'aberdaron', 'borth', 'lossiemouth', 'skirza', 'balnakeil',
  'maze', 'westportkintyre', 'crudenbay', 'whiterocks', 'benone', 'tullan', 'marblehill', 'belderrig',
  'ballyheigue', 'banna', 'ventry', 'stfinians', 'redstrand', 'owenahincha', 'annestown', 'brittas',
  'scivu', 'putzuidu', 'bombarde', 'portopino', 'isolarossa', 'poetto', 'arenzano', 'ilsale',
  'fortedeimarmi', 'sperlonga', 'mondello', 'torrecanne', 'saltstein', 'hellesto', 'hirtshals', 'blokhus',
  'sondervig', 'tylosand', 'weissenhaus', 'stpeterording', 'egmond', 'texel', 'asilah', 'larache',
  'moulaybousselham', 'skhirat', 'sidibouzid', 'lallafatna', 'souiria', 'tifnit', 'foumeloued', 'virage',
  'toubabdialaw', 'capskirring', 'rivernumbertwo', 'cottontree', 'dixcove', 'adafoah', 'labadi', 'grandpopo',
  'grandbassam', 'sassandra', 'portoalegrestp', 'namibe', 'diazpoint', 'hentiesbay', 'paternoster', 'bettysbay',
  'voelklip', 'oysterbay', 'sardiniabay', 'portedward', 'warnerbeach', 'zinkwazi', 'barramoz', 'xaixai',
  'souillac', 'manapany', 'grandansemahe', 'watamu', 'tabarka', 'shamora', 'frenchbeach', 'wada',
  'iioka', 'hiraiso', 'kujihama', 'isohara', 'yotsukura', 'shichigahama', 'chigasaki', 'zushi',
  'irago', 'kushimoto', 'uchizuma', 'kanegahama', 'kakudahama', 'uradome', 'ingu', 'bongsudae',
  'sokcho', 'yonghwa', 'ihotaewoo', 'sagye', 'jinshan', 'chenggong', 'dadonghai', 'tailongwan',
  'burgossiargao', 'dicasalarin', 'baixep', 'baidai', 'surinbeach', 'kelambu', 'padanggalak', 'ketewel',
  'pererenan', 'yehgangga', 'soka', 'seger', 'mawun', 'belongas', 'nungas', 'boarote',
  'srau', 'karanghaji', 'mandiri', 'wayjambu', 'lampuuk', 'unawatuna', 'kapu', 'kappad',
  'cherai', 'honkys', 'kandooma', 'curlcurl', 'longreef', 'collaroy', 'newportnsw', 'whalebeach',
  'bronte', 'coogee', 'wanda', 'erabeach', 'coledale', 'austinmer', 'woonona', 'towradgi',
  'portkembla', 'shellharbour', 'kiama', 'ulladulla', 'maluabay', 'moruya', 'mysterybay', 'bermagui',
  'pambula', 'belongil', 'brunswickheads', 'pottsville', 'hastingspoint', 'casuarina', 'sharpes', 'minniewater',
  'wooli', 'vallabeach', 'diamondheadnsw', 'harrington', 'tuncurry', 'stockton', 'dudley', 'blacksmiths',
  'toowoonbay', 'forresters', 'copacabananswn', 'killcare', 'broadbeach', 'surfersparadise', 'narrowneck', 'yaroomba',
  'sunshinebeach', 'marcusbeach', 'pointimpossible', 'wyeriver', 'kennettriver', 'skenescreek', 'castlecove', 'peterborough',
  'sorrentoback', 'ryeocean', 'standrewsvic', 'carltonbeach', 'bicheno', 'scamander', 'oceanbeachstrahan', 'portmacdonnell',
  'parsonsbeach', 'mandurah', 'leighton', 'citybeach', 'yanchep', 'tworocks', 'guilderton', 'ledgepoint',
  'matarangi', 'pauanui', 'onemana', 'pouawa', 'oceanbeachhb', 'patea', 'ohawe', 'houghtonbay',
  'paekakariki', 'riversdale', 'smaills', 'karitane', 'papatowai', 'oreti', 'carters', 'punakaiki',
  'hokitika', 'matapouri', 'pataua', 'taupobay', 'anawhata', 'portwaikato', 'mokau', 'maketu',
  'pukehina', 'waiotahi', 'tokomaru', 'anaura', 'sigatoka', 'naufragados', 'solidao', 'pantanodosul',
  'bravafloripa', 'garopaba', 'itapiruba', 'margrossolaguna', 'santamarta', 'rincao', 'barravelha', 'itapoa',
  'praiadeleste', 'praiagrandeubatuba', 'vermelhadosul', 'puruba', 'guaeca', 'toquetoque', 'itanhaem', 'pernambucoguaruja',
  'itaguare', 'riviera', 'castelhanos', 'piratininga', 'pontanegramarica', 'praiaseca', 'pero', 'riodasostras',
  'cavaleiros', 'trindade', 'jacaraipe', 'setiba', 'ubu', 'marataizes', 'guarajuba', 'imbassai',
  'sauipe', 'farolbarra', 'itacarezinho', 'olivenca', 'arraialdajuda', 'caraiva', 'atalaia', 'portodegalinhas',
  'serrambi', 'paiva', 'genipabu', 'canoaquebrada', 'icarai', 'puertoviejo', 'bermejo', 'tortugasperu',
  'lapuntacallao', 'chinchorro', 'lascruces', 'santodomingo', 'quintay', 'papudo', 'losvilos', 'pichidangui',
  'tome', 'duao', 'mardelsur', 'mardelaspampas', 'valizas', 'nuqui', 'parguito', 'puertocruz',
  'loscaracas', 'todasana', 'newport56th', 'leocarrillo', 'elmatador', 'bigrockmalibu', 'sunsetblvd', 'pvcove',
  'haggertys', 'emmawood', 'solimar', 'porthueneme', 'shellbeach', 'willowcreek', 'marinastate', 'cowells',
  'anonuevo', 'sharppark', 'bigriver', 'caspar', 'trinidadca', 'grandview', 'oceansideor', 'gleneden',
  'sealrockor', 'waldport', 'rockawayor', 'gearhart', 'grayland', 'copalis', 'moclips', 'rialto',
  'yakutat', 'sunnyisles', 'hollywoodfl', 'fortlauderdale', 'hillsboro', 'palmbeachfl', 'singerisland', 'hobesound',
  'stuartrocks', 'pepperpark', 'wabasso', 'bethune', 'sunglow', 'micklers', 'neptunebeach', 'grayton',
  'mexicobeach', 'okaloosa', 'mustangisland', 'grandisle', 'dauphinisland', 'orangebeach', 'sullivans', 'edisto',
  'cherrygrove', 'killdevil', 'salvo', 'pineknoll', 'holdenbeach', 'northtopsail', 'deweybeach', 'fenwick',
  'strathmere', 'avalonnj', 'monmouthbeach', 'seabright', 'lidobeach', 'shinnecock', 'longnook', 'nantasket',
  'rosarito', 'salsipuedes', 'erendira', 'platanitos', 'litibu', 'tenacatita', 'marquelia', 'puntamaldonado',
  'rocablanca', 'delfines', 'chikura', 'hasaki', 'usuiso', 'arahama', 'oyakaigan', 'uchinada',
  'kisami', 'oiso', 'fukiagehama', 'tomakomai', 'legian', 'lebih', 'parangtritis', 'pangandaran',
  'tanjungsetia', 'pundaquit', 'kodibengre', 'palolem', 'vagator', 'kashid', 'tarkarli', 'panambur',
  'rushikonda', 'tangalle', 'bentota', 'quynhon', 'batuburok', 'guryongpo', 'gwakji', 'mallipo',
  'qijin', 'strandsa', 'astonbay', 'pollok', 'kiddsbeach', 'hagahaga', 'amanzimtoti', 'parkrynie',
  'umdloti', 'saltrock', 'mohammedia', 'capsim', 'tarfaya', 'barceloneta', 'badalona', 'castelldefels',
  'sitges', 'pals', 'santpere', 'patacona', 'elsaler', 'cullera', 'oliva', 'bolnuevo',
  'valdevaqueros', 'calamillor', 'sonserra', 'sonbou', 'prado', 'carro', 'almanarre', 'castelnice',
  'setelido', 'grandemotte', 'leucate', 'canet', 'capodifeno', 'castiglione', 'anzio', 'sabaudia',
  'serapo', 'capovaticano', 'scalea', 'scoglitti', 'playacatania', 'senigallia', 'pescara', 'solanas',
  'kyparissia', 'zacharo', 'kathisma', 'agiosgordios', 'riva', 'agva', 'karaburunist', 'patara',
  'jiyeh', 'velikaplaza', 'kamchia', 'shkorpilovtsi', 'burgas', 'sozopol', 'goldensands', 'vamaveche',
  'costinesti', 'mamaia', 'batumi', 'kobuleti', 'sochi', 'leba', 'wladyslawowo', 'kolobrzeg',
  'dziwnow', 'ustka', 'kuhlungsborn', 'prerow', 'rantum', 'ijmuiden', 'katwijk', 'hoekvanholland',
  'castricum', 'petten', 'vlissingen', 'knokke', 'depanne', 'sola', 'raftcove', 'sanjosef',
  'pointnopoint', 'hirtles', 'pointmichaud', 'ingonish', 'invernessns', 'uveroalto', 'najayo', 'longbayjm',
  'santamariadelmar', 'playacanoa', 'oceanpark', 'inches', 'maili', 'nanakuli', 'barberspoint', 'hauula',
  'paukukalo', 'wailua', 'malabar', 'wombarra', 'bellambi', 'fairymeadow', 'warilla', 'minnamurra',
  'gerroa', 'lakeconjola', 'narrawallee', 'pebblybeach', 'rosedalensw', 'congo', 'dalmeny', 'aslings',
  'redrock', 'arrawarra', 'sapphirebeach', 'boambee', 'northhaven', 'budgewoi', 'tugun', 'nobbybeach',
  'mudjimba', 'currimundi', 'mainbeachstraddie', 'bancoora', 'pointroadknight', 'marengo', 'princetown', 'killarneyvic',
  'mallacoota', 'waratahbay', 'chitonrocks', 'tunkalilla', 'swanbourne', 'singleton', 'prestonbeach', 'binningup',
  'canalrocks', 'hamelinbay', 'windyharbour', 'salmonholes', 'hopetoun', 'horrocks', 'orewa', 'onetangi',
  'medlands', 'kuaotunu', 'whangapoua', 'bowentown', 'matata', 'porangahau', 'akitio', 'tora',
  'otaki', 'foxton', 'kaiiwi', 'urenui', 'oceanbeachkawhia', 'ruapuke', 'kakapoint', 'kakanui',
  'waikuku', 'hickorybay', 'lebonsbay', 'magnetbay', 'rarangi', 'shichirigahama', 'baganga', 'atlantida',
  'pinhal', 'arroiodosal', 'hermenegildo', 'ilhacomprida', 'playasandiego', 'costadelsol', 'elespino', 'playaventura',
  'trails', 'thousandsteps', 'victoriabeach', 'surfsideca', 'morrostrand', 'mitchellscove', 'sangregorio', 'nyebeach',
  'beverlybeach', 'heceta', 'rubybeach', 'chinabeach', 'oceanisle', 'greenhill', 'horseneck', 'keybiscayne',
  'pulpos', 'negritos', 'colan', 'laboca', 'zapallar', 'lagunaverde', 'taltal', 'chanaral',
  'puntarubia', 'orense', 'reta', 'marchiquita', 'etretat', 'malo', 'wissant', 'puntahidalgo',
  'martianez', 'pozoizquierdo', 'costateguise', 'arrieta', 'sotavento', 'cofete', 'puertonaos', 'pauldomar',
  'machico', 'santabarbaraacores', 'populo', 'praiavitoria', 'quebracanela', 'kololi', 'teriberka', 'ventanas',
  'uvita', 'siriu', 'sonhosc', 'picarras', 'amores', 'bravabuzios', 'boulderslennox', 'grassyhead',
  'manningpoint', 'blackheadbeach', 'onemileps', 'teewah', 'forrestcaves', 'harmershaven', 'capeconran', 'hansonbay',
  'dongara', 'contos', 'binalong', 'fourmilecreek', 'opoutere', 'glinks', 'tomahawk', 'allansbeach',
  'warrington', 'hartlandquay', 'whitsand', 'southerndown', 'westangle', 'marloes', 'aberystwyth', 'porthceiriad',
  'stonehaven', 'eyemouth', 'thorntonloch', 'machirbay', 'portstewart', 'curracloe', 'sandsend', 'seatoncarew',
  'seaham', 'sandhaven', 'embleton', 'eastrunton', 'camber', 'perdidokey', 'rosemarybeach', 'stgeorgeisland',
  'jamaicabeach', 'quintana', 'malaquite', 'lunalaunion', 'tabatinga', 'cunhau', 'jacuma', 'coruripe',
  'mangueseco', 'baixio', 'itacimirim', 'pradoba', 'cumuruxatiba', 'conceicaobarra', 'manguinhos', 'itaipava',
  'tirua', 'curinanco', 'pucatrihue', 'marbrava', 'salaverry', 'sanjoselambayeque', 'puertoeten', 'camana',
  'ilo', 'lafonda', 'praiadarocha', 'praiadefaro', 'falesia', 'mutriku', 'rostro', 'barranan',
  'sardinero', 'santamarinarib', 'portoalabe', 'hatterasvillage', 'masonboro', 'sidirahal', 'vinetapoint', 'mile14',
  'lanord', 'bourdaines', 'santocha', 'litetmixe', 'pinsec', 'sablesdor', 'labarre', 'grandeplage',
  'marbellabiarritz', 'milady', 'cenitz', 'conches', 'sauveterre', 'saintjeandemonts', 'portlin', 'leshuttes',
  'porsmilin', 'gavres', 'lepouldu', 'vauville', 'lerozel', 'barneville', 'dieppe', 'equihen',
  'hardelot', 'letouquet', 'ricanto', 'ostriconi', 'armintza', 'ogella', 'gaztetape', 'azkorri',
  'cuchia', 'comillas', 'elbrusco', 'laespasa', 'esmelle', 'orzan', 'caion', 'malpica',
  'soesto', 'lires', 'louro', 'corrubedo', 'bolonia', 'loslances', 'santamariacadiz', 'labarrosa',
  'matalascanas', 'mazagon', 'puntaumbria', 'lamanga', 'guardamar', 'gandia', 'esutrenc', 'calaagulla',
  'calatirant', 'maspalomas', 'sanandres', 'latejita', 'carreco', 'apulia', 'viladoconde', 'buarcos',
  'pedrabranca', 'saolourenco', 'comporta', 'melides', 'santoandre', 'saotorpes', 'mareta', 'martinhal',
  'ingrina', 'meiapraia', 'alvor', 'quarteira', 'lugardebaixo', 'milicias', 'aguadalto', 'almoxarife',
  'santocristo', 'recco', 'bonassola', 'spotorno', 'finaleligure', 'tirrenia', 'castiglioncello', 'cecina',
  'sanvincenzo', 'ladispoli', 'capocotta', 'torvaianica', 'nettuno', 'terracina', 'paestum', 'tropea',
  'soverato', 'torredellorso', 'baiaverde', 'vieste', 'civitanova', 'rimini', 'marinaravenna', 'termoli',
  'puntabraccetto', 'marinaragusa', 'portopalo', 'isoladellefemmine', 'cefalu', 'isarutas', 'piscinas', 'torredeicorsari',
  'badesi', 'renamajore', 'costarei', 'towan', 'northcott', 'duckpool', 'tregardock', 'godrevy',
  'haylecornwall', 'gunwalloe', 'seatoncornwall', 'tregantle', 'southbourne', 'milford', 'freshwaterbay', 'seaford',
  'sheringham', 'seapalling', 'southwold', 'blyth', 'cullercoats', 'roker', 'marske', 'skinningrove',
  'robinhoodsbay', 'scarbnorthbay', 'seascale', 'stbees', 'coneybeach', 'porteynon', 'cefnsidan', 'tenbysouth',
  'druidston', 'newportsands', 'porthoer', 'trecastell', 'harlech', 'brora', 'cullen', 'balmedie',
  'niggbay', 'kingsbarns', 'balephuil', 'tolsta', 'strathy', 'torrisdale', 'aughris', 'lettergesh',
  'ardmore', 'culdaff', 'narin', 'ballycastle', 'whiteparkbay', 'fano', 'thorsminde', 'lonstrup',
  'heringsdorf', 'rerik', 'bergenaanzee', 'callantsoog', 'westkapelle', 'dehaan', 'blankenberge', 'sandhammaren',
  'skrea', 'pavilosta', 'liepaja', 'melnrage', 'sventoji', 'capghir', 'imiouaddar', 'haouzia',
  'temara', 'achakar', 'sidiwassay', 'plageblanche', 'akhfennir', 'boujdour', 'birdrock', 'warmwater',
  'churches', 'sanclementepier', 'capobeach', 'strands', 'coronadelmar', 'riverjetties', 'sunsetbeachca', 'goldenwest',
  'torrancebeach', 'latigo', 'paradisecove', 'trancas', 'nicholascanyon', 'faria', 'pfeiffer', 'martinsbeach',
  'tolovana', 'archcape', 'roadsend', 'horsfall', 'shishi', 'spanishhouse', 'patrick', 'loriwilson',
  'jettypark', 'blowingrocks', 'lantana', 'dania', 'venicefl', 'bocachica', 'peaisland', 'croatan',
  'bayhead', 'longport', 'stoneharbor', 'ditchplains', 'amagansett', 'charlestownbw', 'coastguardbeach', 'newcombhollow',
  'headofthemeadow', 'egyptbeach', 'brantrock', 'drakesisland', 'tonggs', 'kahanabay', 'honokohau', 'dtfleming',
  'spreckelsville', 'donkeybeach', 'halawa', 'summerville', 'cherryhill', 'rissers', 'cavendish', 'marchiquitapr',
  'camalu', 'puntacanoas', 'puntamarquez', 'isladelapiedra', 'anclote', 'mayto', 'majahua', 'bacocho',
  'aguablanca', 'sanjosegt', 'laslisas', 'maculis', 'playasantana', 'elcoco', 'chacocente', 'casares',
  'salinasgrandes', 'laspenitas', 'playacarmen', 'carrillo', 'zancudo', 'adicora', 'chirimena', 'cata',
  'guacuco', 'lastunas', 'santamarianita', 'crucita', 'same', 'cherrepe', 'caballeros', 'mejia',
  'lasmachas', 'bravaiquique', 'losmolles', 'cachagua', 'eltabo', 'cartagenachile', 'cocholgue', 'laraquete',
  'quidico', 'queule', 'maicolpue', 'ostende', 'mardecobo', 'laperla', 'pehuenco', 'santateresauy',
  'aguasdulces', 'puntanegrauy', 'quintao', 'xangrila', 'magisterio', 'ouvidor', 'ibiraquera', 'morroconventos',
  'arroiodosilva', 'estaleiro', 'mariscal', 'barradosul', 'caioba', 'mongagua', 'pitangueiras', 'boraceia',
  'boicucanga', 'prumirim', 'joatinga', 'copacabanario', 'ipanema', 'camboinhas', 'barrademarica', 'grussai',
  'praiadosono', 'itaparicavv', 'guriri', 'meaipe', 'jeribucacu', 'espelho', 'flamengossa', 'amaralina',
  'vilasdoatlantico', 'barradojacuipe', 'subauma', 'sitiodoconde', 'praiadosaco', 'muroalto', 'intermares', 'cotovelo',
  'gostoso', 'pecem', 'cumbuco', 'lagoinhace', 'flecheiras', 'portodasdunas', 'morrobranco', 'barragrandepi',
  'conceicaonoronha', 'bilgola', 'corrimal', 'wollongongcity', 'bendalong', 'surfbeachnsw', 'suffolkpark', 'newcastlebeach',
  'barbeach', 'shellycc', 'bilinga', 'miamigc', 'mainbeachgc', 'kingsbeach', 'dickybeach', 'mooloolaba',
  'maroochydore', 'barwonbluff', 'sandypoint', 'gibsonsteps', 'marionbay', 'friendlybeaches', 'seafordsa', 'knightsbeach',
  'lefthanders', 'wilyabrup', 'falcon', 'myalup', 'mandalaybeach', 'fourthbeach', 'backbeachgeraldton', 'coronation',
  'blowholes', 'cablebeach', 'indicators', 'whalebaynz', 'ngarunui', 'backbeachnp', 'breakerbay', 'waikanaegis',
  'teawanga', 'stkildadunedin', 'blaketown', 'rapahoe', 'seminyak', 'kutalombok', 'lakeypipe', 'perosumba',
  'klayar', 'pantaipanjang', 'katakai', 'moriya', 'takahagi', 'kawarago', 'shinmaiko', 'yuriage',
  'kotohiki', 'hakuto', 'keya', 'yumigahama', 'iritahama', 'shirasuka', 'akabane', 'minabe',
  'shishikui', 'nahari', 'takanabe', 'cemento', 'ombeach', 'murdeshwar', 'karwar', 'bekal',
  'payyambalam', 'alappuzha', 'kollam', 'gopalpur', 'anjuna', 'colva', 'ganpatipule', 'nagaon',
  'polhena', 'anbang', 'hococ', 'kamala', 'bangtao', 'karon', 'pakweep', 'tanjungaru',
  'telukcempedak', 'mangsang', 'hamdeok', 'pyoseon', 'kkotji', 'toucheng', 'qixingtan', 'zhujiajian',
  'blouberg', 'milnerton', 'kleinmond', 'grotto', 'pearlybeach', 'struisbaai', 'arniston', 'diasbeach',
  'grootbrak', 'keurboomstrand', 'maitlands', 'schoenmakerskop', 'humewood', 'boknesstrand', 'kleinemonde', 'morganbay',
  'mazeppa', 'southbroom', 'uvongo', 'lamercy', 'tinleymanor', 'blythedale', 'saly', 'lome',
  'sanpedro', 'malindi', 'guinjata', 'morrungulo', 'taharuu', 'pointvenus', 'lediamant', 'maracas',
  'lascuevas', 'surfsidefl', 'hallandale', 'lbts', 'highlandbeach', 'oceanridge', 'waltonrocks', 'roundisland',
  'paradisebeachfl', 'huguenot', 'littletalbot', 'kiawah', 'washout', 'litchfield', 'caswellbeach', 'figureeight',
  'waves', 'mantoloking', 'harveycedars', 'beachhaven', 'diamondbeach', 'capemaypoint', 'avonbythesea', 'oceanbeachfi',
  'breezypoint', 'watchhill', 'southshorelc', 'ballston', 'humarock', 'nahant', 'cranebeach', 'fortpickens',
  'inletbeach', 'sanluispass', 'sargent', 'warriewood', 'bungan', 'marley', 'burningpalms', 'coalcliff',
  'kioloa', 'durras', 'guerillabay', 'wallagalake', 'turabeach', 'skennars', 'shellyballina', 'corindi',
  'diggers', 'ninemile', 'elizabethbeach', 'annabay', 'lakesbeach', 'bateaubay', 'northavoca', 'northburleigh',
  'castaways', 'alexandriabay', 'aireysinlet', 'cumberlandriver', 'koonya', 'shoreham', 'summerland', 'squeakybeach',
  'woodside', 'seaspray', 'maslin', 'aldinga', 'sellicks', 'floreat', 'mullaloo', 'burnsbeach',
  'quinnsrocks', 'boranup', 'lightsbeach', 'langsbeach', 'tongaporutu', 'onaero', 'manaia', 'plimmerton',
  'hicksbay', 'karamea', 'penthievre', 'donnant', 'kerloch', 'penhat', 'treompan', 'pirou',
  'agon', 'sangatte', 'berck', 'fortmahon', 'fecamp', 'saintadresse', 'sionsurlocean', 'grandecote',
  'petitnice', 'lesleques', 'palavas', 'espiguette', 'gruissan', 'saintcyprien', 'argeles', 'tiuccia',
  'saturraran', 'galizano', 'artedo', 'ponzos', 'morouzos', 'areaviveiro', 'arou', 'riosieira',
  'chipiona', 'torredelpuerco', 'zahora', 'atlanterra', 'islacristina', 'elportil', 'mindelo', 'aguda',
  'esmoriz', 'saojacinto', 'costadelavos', 'leirosa', 'portonovo', 'lagoaalbufeira', 'praiadaluz', 'armacaodepera',
  'marinadimassa', 'lidodicamaiore', 'santasevera', 'baiadomizia', 'praiaamare', 'amantea', 'portocesareo', 'isarenas',
  'popotla', 'playastijuana', 'playahermosaens', 'eltule', 'puntagordabcs', 'playanorte', 'destiladeras', 'mexiquillo',
  'copala', 'barracopalita', 'bocadelcielo', 'puertomadero', 'laflor', 'playagarza', 'matapaloquepos', 'playatortuga',
  'bonitalimon', 'guanico', 'guachalito', 'mendihuaca', 'bocagrande', 'manglaralto', 'puertocayo', 'atacames',
  'huarmey', 'pupuya', 'boyeruca', 'puertosaavedra', 'mardeajo', 'capaonovo', 'itapevatorres', 'gaivota',
  'ribanceira', 'palmasgcr', 'prainhasfs', 'toninhas', 'aventureiro', 'pontalipiranga', 'corumbau', 'algodoes',
  'taipudefora', 'morere', 'pirambu', 'gaibu', 'buziosrn', 'iguapece', 'majorlandia', 'mundau',
  'prea', 'salinopolis', 'boldro', 'shirako', 'kimigahama', 'tsujido', 'tatadohama', 'imaihama',
  'maisaka', 'shichirimihama', 'yunohama', 'namiita', 'sacheon', 'jumunjin', 'songjiho', 'shanyuan',
  'patar', 'pandawa', 'sawangan', 'trevone', 'crooklets', 'combesgate', 'bournemouthpier', 'highcliffe',
  'chalebay', 'mundesley', 'caister', 'gorleston', 'bridlington', 'crimdon', 'whitleybay', 'newbiggin',
  'alnmouth', 'porterin', 'poppit', 'llanddwyn', 'dornoch', 'hopeman', 'luskentyre', 'bosta',
  'mangersta', 'killahoey', 'rossbeg', 'maghery', 'fintra', 'murvagh', 'whitestrand', 'longstrand',
  'tyrella', 'blavand', 'mellbystrand', 'agadirbeach', 'malika', 'tokeh', 'mistycliffs', 'strandfontein',
  'monwabisi', 'jongensfontein', 'seaview', 'orientbeach', 'mbotyi', 'mtunzini', 'sodwana', 'chidenguele',
  'ubara', 'katsuura', 'hitotsumatsu', 'toyoumi', 'teacapan', 'novillero', 'barracoyuca', 'tonameca',
  'keaukaha', 'lannenec', 'ansededinan', 'trescadec', 'leveillon', 'praiadonorte', 'portodinheiro', 'amoreira',
  'rockawaypacifica', 'kellyscove', 'sloat', 'fortfunston', 'wickaninnish', 'uretiti', 'tawharanui', 'ossodabaleia',
  'legua', 'salgado', 'delrey', 'praiaformosa', 'janubio', 'ajuy', 'losmolinos', 'mesadelmar',
  'lalaja', 'playaingles', 'vallegranrey', 'tazacorte', 'lidolatina', 'fontanebianche', 'sanleone', 'marinella',
  'portosangiorgio', 'francavilla', 'jesolo', 'lignano', 'kalogria', 'irakli', 'karadere', 'primorsko',
  'sinemorets', 'doimai', 'ureki', 'anapa', 'zelenogradsk', 'debki', 'kaseberga', 'sanbernardo',
  'santateresita', 'sanclementetuyu', 'valeria', 'centinela', 'laaguada', 'arachania', 'elchorro', 'bravapde',
  'puntacabras', 'sanantoniodelmar', 'pescaderobcs', 'andicuri', 'guanabay', 'kawabay', 'polihua', 'pasagshak',
  'hugpoint', 'pointreyes', 'manchester', 'navarro', 'westportunion', 'biglagoon', 'goldbluffs', 'raggedpoint',
  'millcreek', 'carmelriver', 'southmission', 'bulli', 'coniston', 'shoalhavenheads', 'dolphinpoint', 'pointarkwright',
  'buddina', 'kawana', 'tallebudgera', 'mindarie', 'seabird', 'portnoarlunga', 'waimairi', 'birdlingsflat',
  'patitipoint', 'purakaunui', 'kanaha', 'puamana', 'kahepoint', 'kitchenwindows', 'cubelles', 'torredembarra',
  'peniscola', 'benicassim', 'canetberenguer', 'pinedo', 'tavernes', 'deveses', 'arenales', 'lamata',
  'aguilas', 'sarapita', 'calamesquida', 'migjorn', 'sestrilevante', 'marinagrosseto', 'feniglia', 'montalto',
  'tarquinia', 'castelvolturno', 'licola', 'palinuro', 'diamante', 'gizzeria', 'portopalomenfi', 'platamona',
  'bosamarina', 'martimdesa', 'maranduba', 'pecadomacae', 'barradesaojoao', 'barradofurado', 'praiadomorro', 'iriri',
  'guaibim', 'praiadasfontes', 'pontaldemaceio', 'bocadeapiza', 'colola', 'bogueinlet', 'fortfisher', 'springmaid',
  'apollobeachfl', 'spanishriver', 'northbeachmiami', 'eastons', 'scarboroughri', 'silverstrandoxnard', 'elsegundoca', 'pacificbeachwa',
  'moolack', 'pistolriver', 'kenningtoncove', 'martil', 'aintaya', 'ainelturck', 'rafraf', 'elliots',
  'auroville', 'yarada', 'dewata', 'ambalangoda', 'diguisit', 'hyeopjae', 'hwasun', 'masceti',
  'tampah', 'ujunggenteng', 'telengria', 'airmanis', 'nymindegab', 'tversted', 'wenningstedt', 'kniepsand',
  'borkum', 'ameland', 'koksijde', 'jastrzebiagora', 'mielno', 'swinoujscie', 'rowy', 'palanga',
  'nida', 'ventspils', 'axim', 'sangano', 'pontamamoli', 'ifaty', 'twinharbors', 'klamath',
  'samoa', 'mattole', 'greenwood', 'doran', 'limantour', 'greyhoundrock', 'zmudowski', 'fletchercove',
  'lostubos', 'puertonuevo', 'cuadai', 'langco', 'mullaway', 'urunga', 'bonnyhills', 'saltwaternsw',
  'littlebay', 'capeschanck', 'williamsons', 'marlo', 'westbeachesp', 'arthurriver', 'arawhata', 'kaupokonui',
  'owhiro', 'kairakau', 'sailorsgrave', 'fossilbeach', 'kujigawa', 'akamba', 'lalagune', 'sonabia',
  'sanjuandelaarena', 'sabon', 'arusi', 'cuyagua', 'shalun', 'saud', 'kemasik', 'muzhappilangad',
  'maravanthe', 'agonda', 'diveagar', 'koggala', 'talalla', 'inani', 'bijilo', 'jacqueville',
  'lambertsbay', 'portnolloth', 'annamaria', 'clearwater', 'treasureisland', 'margara', 'guajataca', 'sinclairsbay',
  'vigdel', 'kandestederne', 'haverdal', 'gwangalli', 'anmok', 'nyanyi', 'pasut', 'gumicik',
  'siyut', 'lepang', 'dinadiawan', 'nhatle', 'jici', 'goraebul', 'kallady', 'tantan',
  'sunrisebeach', 'vilar', 'trezhir', 'poldhu', 'infiernillo', 'pokaibay', 'covadovapor', 'minedor',
  'govelle', 'flatrock', 'cudgen', 'tenorio', 'abrico', 'galheta', 'covachos', 'calatorta',
  'bradleybeach', 'allenhurst', 'oceangrovenj', 'seasidepark', 'northwildwood', 'wildwoodcrest', 'margatenj', 'normandybeach',
  'barnegatlight', 'atlanticbeachny', 'ponquogue', 'easthampton', 'cupsogue', 'southbethany', 'buxton', 'surfsidesc',
  'beverlybeachfl', 'marineland', 'butlerbeach', 'siestakey', 'diamondbeachnsw', 'flynnsbeach', 'northentrance', 'norahhead',
  'gamboa', 'tabatingasp', 'enseadaguaruja', 'pepe', 'reservario', 'chambredamour', 'arrigunaga', 'perranuthnoe',
  'vilacha', 'madalenagaia', 'santarita', 'abano', 'moinhodebaixo', 'abertanova', 'pessegueiro', 'aivados',
  'carvalhalodemira', 'carriagem', 'telheiro', 'burgau', 'portodemos', 'risnoja', 'amelie', 'penningtonkzn',
  'umkomaas', 'hibberdene', 'ramsgate', 'trafalgar', 'umtentweni', 'keimouth', 'onrus', 'oceanreefpark',
  'phipps', 'humiston', 'indianharbour', 'anastasia', 'sunsetbeachnc', 'standrewsfl', 'mackenziebeach',
  'mengening', 'berawa', 'magicsands', 'lymans', 'uchiumi', 'takesaki', 'hahei', 'bristol',
  'lagide', 'molheleste', 'tropicalsumbawa', 'silverrock', 'portixeddu', 'minicapo', 'holebeach', 'strangles',
  'contrebandiers', 'uppertrestles', 'pipescardiff', 'stonesteps', 'penon', 'culsnus', 'panoramas', 'northsteyne',
  'elephantrock',
];
export const ONBOARDING_PICKS = ['trestles', 'pipeline', 'jbay', 'uluwatu', 'nazare', 'snapper', 'mundaka'];

export const HOUR_LABELS = ['5a', '7a', '9a', '11a', '1p', '3p', '5p', '7p'];
export const HOUR_INDICES = [5, 7, 9, 11, 13, 15, 17, 19];
export const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

// The spots someone actually chose, as distinct from `order` itself -- which starts as the
// entire built-in catalog (every id in ORDER above, currently 718 of them) and would call all
// of them "yours" if listed as-is. An id in `order` that is not in ORDER is, by construction,
// one a person searched for and added, which is the line NavDrawer, ProfileView and AlertSheet
// all need to draw between what shipped with the app and what someone chose. Drawn once here
// rather than three times slightly differently.
export function addedSpotIds(order, spots) {
  return order.filter((id) => spots[id] && !ORDER.includes(id));
}

// `addedSpotIds`, with the go-to spot pinned to the front and deduplicated -- the shape every
// "your spots" picker in the app actually shows: the one you surf by default, then whatever
// else you added.
export function yourSpotIds(order, spots, goToId) {
  const added = addedSpotIds(order, spots);
  return [goToId, ...added.filter((id) => id !== goToId)].filter((id) => spots[id]);
}

// Find built-in spots by name, city, state or country.
//
// The search sheet only ever geocoded arbitrary place names, which was fine when the catalog
// was a few dozen spots you could scroll past. At 300+ there is otherwise no way to reach one
// by name, and searching for a spot that is already here would offer to add a *duplicate* of it
// as a custom spot.
//
// Every word of the query has to land somewhere, but they may land in different places and in
// any order, so "Herzliya Israel" reaches a spot whose region reads "Herzliya, Israel". Matching
// the query as one string could not: the comma sits between the two words the user typed, and a
// single `includes` spans it for nobody. That is not an edge case — naming the country is the
// obvious way to disambiguate a city, and it silently returned nothing at all.
//
// Ranked so an exact name match beats a name that merely starts with the query, which beats one
// that contains it, which beats a match that needed the region — otherwise typing "Bells" can
// put a beach in another hemisphere above Bells Beach.
export function searchCatalog(spots, query, limit = 8) {
  const q = foldText(query);
  if (q.length < 2 || !spots) return [];
  const tokens = q.split(' ');
  const scored = [];
  for (const [id, s] of Object.entries(spots)) {
    if (!s || !s.name) continue;
    const name = foldText(s.name);
    const haystack = spotSearchText(s);
    let rank = null;
    if (name === q) rank = 0;
    else if (name.startsWith(q)) rank = 1;
    else if (name.includes(q)) rank = 2;
    else if (tokens.every((t) => haystack.includes(t))) {
      // A query whose words are spread across the name and the region still ranks above one the
      // name had no part in, so "Bells Beach Australia" leads with Bells Beach.
      rank = tokens.some((t) => name.includes(t)) ? 3 : 4;
    }
    if (rank != null) scored.push({ id, spot: s, rank });
  }
  scored.sort((a, b) => a.rank - b.rank || a.spot.name.localeCompare(b.spot.name));
  return scored.slice(0, limit);
}
