// Seed spot data. See HANDOFF.md for provenance notes — most of these were
// re-verified against real sources, a few were corrected (see git history).
//
// `swellWindow: [from, to]` is the compass arc (clockwise) a spot actually receives swell
// from, and `bestTide` is the tide it works best on ('low' | 'mid' | 'high' | 'all'). Both are
// optional: spots without them fall back to an arc derived from `offshoreDeg` — see
// lib/spotmodel.js, which explains why the derived arc is only a starting point and why the
// rule it replaced actively penalised the best waves in this list.
export const SPOTS = {
  trestles: { name: 'Lower Trestles', region: 'San Clemente, CA', blurb: 'Cobblestone point wrapping into long, workable walls. Best before the wind fills in.', lat: 33.3825, lon: -117.5972, offshoreDeg: 60, swellWindow: [180, 230], bestTide: 'mid' },
  blacks: { name: 'Blacks Beach', region: 'La Jolla, CA', blurb: 'Deep submarine canyon keeps it offshore-groomed most of the day. Powerful and hollow.', lat: 32.8991, lon: -117.2528, offshoreDeg: 90, swellWindow: [260, 310], bestTide: 'all' },
  rincon: { name: 'Rincon', region: 'Santa Barbara, CA', blurb: 'Long, playful walls peeling down the point. Small today, but silky smooth.', lat: 34.3739, lon: -119.4763, offshoreDeg: 350, swellWindow: [260, 310], bestTide: 'mid' },
  wedge: { name: 'The Wedge', region: 'Newport Beach, CA', blurb: 'Ledgy, close-interval peaks off the jetty. Heavy, and not for the faint of heart.', lat: 33.5952, lon: -117.8822, offshoreDeg: 30, swellWindow: [180, 230], bestTide: 'all' },
  pipeline: { name: 'Pipeline', region: 'Oahu, Hawaii', blurb: "World-famous reef barrel on the North Shore. Heavy, shallow, and unforgiving when it's on.", lat: 21.6647, lon: -158.0538, offshoreDeg: 200, swellWindow: [290, 350], bestTide: 'mid' },
  teahupoo: { name: "Teahupo'o", region: 'Tahiti, French Polynesia', blurb: 'One of the heaviest, thickest waves on the planet, breaking over shallow coral.', lat: -17.8570, lon: -149.2680, offshoreDeg: 20, swellWindow: [190, 230], bestTide: 'low' },
  jbay: { name: 'Jeffreys Bay', region: 'Eastern Cape, South Africa', blurb: 'Long, high-speed right point — one of the best walls in the world when it lines up.', lat: -34.0489, lon: 24.9087, offshoreDeg: 325, swellWindow: [190, 240], bestTide: 'all' },
  uluwatu: { name: 'Uluwatu', region: 'Bali, Indonesia', blurb: "Dramatic reef break beneath a clifftop temple, with several sections down the point.", lat: -8.8290, lon: 115.0870, offshoreDeg: 50, swellWindow: [200, 250], bestTide: 'mid' },
  snapper: { name: 'Snapper Rocks', region: 'Gold Coast, Australia', blurb: 'The Superbank — impossibly long, fast right points when the sand banks line up.', lat: -28.1590, lon: 153.5470, offshoreDeg: 250, swellWindow: [100, 160], bestTide: 'all' },
  nazare: { name: 'Nazaré', region: 'Portugal', blurb: 'Home to some of the biggest waves ever surfed, thanks to an underwater canyon offshore.', lat: 39.6033, lon: -9.0705, offshoreDeg: 85, swellWindow: [280, 330], bestTide: 'all' },
  chicama: { name: 'Chicama', region: 'La Libertad, Peru', blurb: 'The longest left-hand point wave in the world — rides can last over a minute.', lat: -7.7000, lon: -79.4500, offshoreDeg: 135, swellWindow: [190, 230], bestTide: 'all' },
  raglan: { name: 'Raglan', region: 'Waikato, New Zealand', blurb: 'Classic left point break, one of the most consistent walls in the Southern Hemisphere.', lat: -37.8010, lon: 174.8710, offshoreDeg: 95, swellWindow: [220, 270], bestTide: 'mid' },
  puertoescondido: { name: 'Puerto Escondido', region: 'Oaxaca, Mexico', blurb: "Nicknamed the Mexican Pipeline — a powerful, sandy-bottom beach break barrel.", lat: 15.8720, lon: -97.0767, offshoreDeg: 15, swellWindow: [170, 220], bestTide: 'all' },
  hossegor: { name: 'Hossegor', region: 'France', blurb: 'Punchy, powerful Atlantic beach breaks that host a stop on the world tour.', lat: 43.6640, lon: -1.4400, offshoreDeg: 90, swellWindow: [260, 320], bestTide: 'all' },
  mundaka: { name: 'Mundaka', region: 'Basque Country, Spain', blurb: 'A world-class left river-mouth wave that peels around a sandbar.', lat: 43.4070, lon: -2.6990, offshoreDeg: 180, swellWindow: [300, 340], bestTide: 'mid' },
  cloudbreak: { name: 'Cloudbreak', region: 'Mamanuca Islands, Fiji', blurb: 'A world-class reef pass left, breaking over shallow coral in the open ocean.', lat: -17.8600, lon: 177.2000, offshoreDeg: 130, swellWindow: [180, 230], bestTide: 'mid' },
  skeletonbay: { name: 'Skeleton Bay', region: 'Namibia', blurb: 'A freakishly long, mechanical sand-point left along a remote desert coastline.', lat: -22.9590, lon: 14.4930, offshoreDeg: 165, swellWindow: [200, 240], bestTide: 'all' },
  pavones: { name: 'Pavones', region: 'Golfo Dulce, Costa Rica', blurb: 'One of the longest lefts in the world, wrapping into a jungle-lined bay.', lat: 8.3830, lon: -83.1500, offshoreDeg: 25, swellWindow: [180, 230], bestTide: 'mid' },
  fistral: { name: 'Fistral Beach', region: 'Newquay, Cornwall, UK', blurb: "The UK's best-known beach break, exposed to the full force of the Atlantic.", lat: 50.4160, lon: -5.1020, offshoreDeg: 90, swellWindow: [260, 320], bestTide: 'all' },
  anchorpoint: { name: 'Anchor Point', region: 'Taghazout, Morocco', blurb: 'A classic North African right point, long and mellow when it wraps in clean.', lat: 30.5460, lon: -9.7100, offshoreDeg: 85, swellWindow: [280, 330], bestTide: 'mid' },
  margaretriver: { name: 'Margaret River', region: 'Western Australia', blurb: 'Powerful, chilly reef and point breaks along a wild stretch of coastline.', lat: -33.9750, lon: 115.0750, offshoreDeg: 90, swellWindow: [200, 250], bestTide: 'all' },
  montauk: { name: 'Montauk', region: 'New York, USA', blurb: 'Classic East Coast beach and reef breaks at the tip of Long Island.', lat: 41.0500, lon: -71.9200, offshoreDeg: 330 },
  arugambay: { name: 'Arugam Bay', region: 'Sri Lanka', blurb: "A long, sandy-bottomed right point on Sri Lanka's east coast.", lat: 6.8400, lon: 81.8300, offshoreDeg: 270, swellWindow: [130, 200], bestTide: 'all' },
  gland: { name: 'G-Land', region: 'East Java, Indonesia', blurb: 'A legendary, remote left reef break inside a jungle bay.', lat: -8.7304, lon: 114.3526, offshoreDeg: 35, swellWindow: [190, 230], bestTide: 'mid' },
  siargao: { name: 'Siargao (Cloud 9)', region: 'Philippines', blurb: 'A hollow, powerful reef pass that put the Philippines on the surfing map.', lat: 9.8000, lon: 126.1660, offshoreDeg: 270, swellWindow: [40, 110], bestTide: 'mid' },
  ericeira: { name: 'Ericeira', region: 'Portugal', blurb: 'A World Surfing Reserve with a cluster of quality points and reefs.', lat: 38.9630, lon: -9.4160, offshoreDeg: 90, swellWindow: [270, 330], bestTide: 'all' },
  desertpoint: { name: 'Desert Point', region: 'Lombok, Indonesia', blurb: 'One of the fastest, longest tube rides on Earth, over sharp reef.', lat: -8.8900, lon: 116.0400, offshoreDeg: 60, swellWindow: [190, 230], bestTide: 'low' },
  tofino: { name: 'Tofino', region: 'Vancouver Island, Canada', blurb: 'Cold-water Pacific beach breaks framed by old-growth rainforest.', lat: 49.1530, lon: -125.9066, offshoreDeg: 90 },
  joaquina: { name: 'Joaquina', region: 'Florianópolis, Brazil', blurb: 'A popular sandy beach break on Floripa island, consistent and crowd-friendly.', lat: -27.6280, lon: -48.4480, offshoreDeg: 270 },
  puntadelobos: { name: 'Punta de Lobos', region: 'Pichilemu, Chile', blurb: "A powerful, rocky left point on Chile's rugged central coast.", lat: -34.4110, lon: -72.0270, offshoreDeg: 90 },
  shonan: { name: 'Shonan', region: 'Kanagawa, Japan', blurb: "Tokyo's home break — accessible and consistent, a train ride from the city.", lat: 35.3060, lon: 139.4870, offshoreDeg: 0 },
  kovalam: { name: 'Kovalam', region: 'Kerala, India', blurb: "A mellow beach break on India's southwestern coast, warm water year-round.", lat: 8.4004, lon: 76.9787, offshoreDeg: 90 },
  caesarea: { name: 'Caesarea', region: 'Israel', blurb: 'A Mediterranean reef break beside the ruins of an ancient Roman harbor.', lat: 32.5000, lon: 34.9040, offshoreDeg: 90, swellWindow: [240, 330], bestTide: 'all' },
  elcotillo: { name: 'El Cotillo', region: 'Fuerteventura, Canary Islands', blurb: "Wind-sculpted beach breaks on the island's rugged north coast.", lat: 28.6800, lon: -14.0080, offshoreDeg: 165 },
  popoyo: { name: 'Popoyo', region: 'Nicaragua', blurb: "A hollow reef break on Nicaragua's Pacific coast, offshore almost every morning.", lat: 11.4731, lon: -86.1270, offshoreDeg: 90 },
  santacatalina: { name: 'Santa Catalina', region: 'Panama', blurb: "A powerful, rocky point break on Panama's Pacific coast.", lat: 7.6330, lon: -81.2680, offshoreDeg: 85 },
  deadmans: { name: 'Deadmans', region: 'Denmark', blurb: "A cold-water North Sea break in Denmark's surf region, best with a groundswell and light wind.", lat: 57.0500, lon: 8.5100, offshoreDeg: 90 },
  muine: { name: 'Mui Ne', region: 'Vietnam', blurb: 'A wind-exposed stretch of coast better known for kitesurfing, but surfable too.', lat: 10.9330, lon: 108.2830, offshoreDeg: 293 },
  laentrada: { name: 'La Entrada', region: 'Ecuador', blurb: "A sandy beach break at the north end of the Olón beach stretch, gentle and beginner-friendly.", lat: -1.7700, lon: -80.7700, offshoreDeg: 90 },
  montoya: { name: 'Montoya', region: 'Punta del Este, Uruguay', blurb: "A rocky point near Punta del Este, one of Uruguay's better-known breaks.", lat: -34.9500, lon: -54.9300, offshoreDeg: 350 },
  darne: { name: 'Darne', region: 'Mauritius', blurb: "A remote left reef break behind Île des Deux Cocos, inside the island's fringing coral.", lat: -20.4200, lon: 57.7000, offshoreDeg: 0 },
  capesolander: { name: 'Cape Solander', region: 'Sydney, Australia', blurb: "An exposed ledge break on the cliffs at Sydney's Kurnell headland.", lat: -34.0010, lon: 151.2330, offshoreDeg: 270 },
  masnou: { name: 'Masnou', region: 'Catalonia, Spain', blurb: 'A Mediterranean beach break just north of Barcelona, small but rideable on a good day.', lat: 41.4780, lon: 2.3160, offshoreDeg: 315 },
  capomarina: { name: 'Capo Marina', region: 'Genoa, Italy', blurb: 'A rocky point break on the Ligurian coast near Genoa.', lat: 44.4000, lon: 8.9500, offshoreDeg: 5 },

  // Second batch — added on request to expand geographic coverage. Same caveat as the
  // original 44: reasonable estimates from available sources, not surveyed. Coordinates for
  // the least-documented of these (Macaronis, Riyue Bay) were verified against cited sources;
  // Lagundri Bay and Jinzun are lower-confidence estimates (no precise published coordinates
  // found) placed near the nearest documented reference point.
  malibu: { name: 'Malibu (Surfrider Beach)', region: 'California, USA', blurb: 'A classic, mechanical right point that helped define modern longboarding.', lat: 34.0369, lon: -118.6786, offshoreDeg: 0, swellWindow: [180, 230], bestTide: 'mid' },
  steamerlane: { name: 'Steamer Lane', region: 'Santa Cruz, CA', blurb: 'A punchy reef/point off a cliffside lighthouse, the heart of Santa Cruz surfing.', lat: 36.9519, lon: -122.0247, offshoreDeg: 30, swellWindow: [260, 320], bestTide: 'mid' },
  mavericks: { name: 'Mavericks', region: 'Half Moon Bay, CA', blurb: 'A cold-water big-wave reef that only wakes up on serious winter swells.', lat: 37.4913, lon: -122.5025, offshoreDeg: 90, swellWindow: [270, 320], bestTide: 'mid' },
  waimeabay: { name: 'Waimea Bay', region: 'Oahu, Hawaii', blurb: "Hawaii's original big-wave proving ground, dormant until the swell is massive.", lat: 21.6392, lon: -158.0656, offshoreDeg: 180, swellWindow: [300, 350], bestTide: 'all' },
  sunsetbeach: { name: 'Sunset Beach', region: 'Oahu, Hawaii', blurb: 'A shifting, powerful North Shore peak that punishes poor positioning.', lat: 21.6754, lon: -158.0400, offshoreDeg: 180, swellWindow: [300, 350], bestTide: 'all' },
  honoluabay: { name: 'Honolua Bay', region: 'Maui, Hawaii', blurb: 'A picture-perfect right point wrapping into a protected jungle bay.', lat: 21.0067, lon: -156.6403, offshoreDeg: 135 },
  hookipa: { name: 'Hookipa', region: 'Maui, Hawaii', blurb: 'Powerful reef break better known today as a windsurfing/kite mecca.', lat: 20.9330, lon: -156.3580, offshoreDeg: 180 },
  sayulita: { name: 'Sayulita', region: 'Nayarit, Mexico', blurb: 'A friendly, playful beach and point break inside a laid-back fishing village.', lat: 20.8700, lon: -105.4419, offshoreDeg: 45 },
  barradelacruz: { name: 'Barra de la Cruz', region: 'Oaxaca, Mexico', blurb: 'A world-class right point through a village-owned reserve, long and rippable.', lat: 15.9280, lon: -96.0670, offshoreDeg: 0 },
  playahermosa: { name: 'Playa Hermosa', region: 'Puntarenas, Costa Rica', blurb: "Costa Rica's most consistent beach break, powerful and popular with pros in training.", lat: 9.5480, lon: -84.5820, offshoreDeg: 45 },
  witchsrock: { name: "Witch's Rock", region: 'Guanacaste, Costa Rica', blurb: 'A remote national-park beach break made famous by Endless Summer II.', lat: 10.7990, lon: -85.6870, offshoreDeg: 90, swellWindow: [200, 250], bestTide: 'all' },
  salsabrava: { name: 'Salsa Brava', region: 'Puerto Viejo, Costa Rica', blurb: "Costa Rica's heaviest wave, a shallow Caribbean reef pass not for beginners.", lat: 9.6550, lon: -82.7530, offshoreDeg: 270 },
  elsunzal: { name: 'El Sunzal', region: 'La Libertad, El Salvador', blurb: "A long, forgiving right point — one of Central America's best learn-to-surf waves.", lat: 13.4930, lon: -89.4460, offshoreDeg: 0, swellWindow: [180, 230], bestTide: 'mid' },
  puntaroca: { name: 'Punta Roca', region: 'La Libertad, El Salvador', blurb: "El Salvador's premier point break, a long, powerful right along a rocky headland.", lat: 13.4880, lon: -89.3220, offshoreDeg: 0 },
  picoalto: { name: 'Pico Alto', region: 'Punta Hermosa, Peru', blurb: "One of South America's premier big-wave reef breaks, south of Lima.", lat: -12.3330, lon: -76.8250, offshoreDeg: 90 },
  mancora: { name: 'Máncora', region: 'Piura, Peru', blurb: 'A long, warm-water left point in a lively northern Peru beach town.', lat: -4.1080, lon: -81.0480, offshoreDeg: 75 },
  guardadoembau: { name: 'Guarda do Embaú', region: 'Santa Catarina, Brazil', blurb: 'A river-mouth right point inside a protected coastal village.', lat: -27.9500, lon: -48.5830, offshoreDeg: 270 },
  itacare: { name: 'Itacaré', region: 'Bahia, Brazil', blurb: 'Jungle-backed beach breaks and points along a laid-back Bahia coastline.', lat: -14.2780, lon: -38.9960, offshoreDeg: 270 },
  rinconpr: { name: 'Rincón', region: 'Puerto Rico', blurb: "Puerto Rico's best-known surf town, with a string of reef and point breaks.", lat: 18.3400, lon: -67.2510, offshoreDeg: 90 },
  soupbowl: { name: 'Soup Bowl', region: 'Bathsheba, Barbados', blurb: "Barbados's premier wave, a punchy Atlantic-facing reef.", lat: 13.2170, lon: -59.5180, offshoreDeg: 270 },
  lasanta: { name: 'La Santa', region: 'Lanzarote, Canary Islands', blurb: 'A powerful, volcanic-reef left on a rugged, wind-exposed coast.', lat: 29.1330, lon: -13.7330, offshoreDeg: 165 },
  elconfital: { name: 'El Confital', region: 'Gran Canaria, Canary Islands', blurb: 'A long left point wrapping around a quiet stretch near Las Palmas.', lat: 28.1580, lon: -15.4460, offshoreDeg: 135 },
  supertubos: { name: 'Supertubos', region: 'Peniche, Portugal', blurb: 'A world-class, barreling beach break that hosts a stop on the world tour.', lat: 39.3490, lon: -9.3830, offshoreDeg: 90, swellWindow: [270, 330], bestTide: 'all' },
  amado: { name: 'Praia do Amado', region: 'Algarve, Portugal', blurb: 'An exposed, reliable beach break near Sagres, a Euro surf-trip staple.', lat: 37.1810, lon: -8.9080, offshoreDeg: 90 },
  thursoeast: { name: 'Thurso East', region: 'Scotland, UK', blurb: 'A cold-water reef point that put Scottish surfing on the map.', lat: 58.5950, lon: -3.5140, offshoreDeg: 180, swellWindow: [340, 50], bestTide: 'mid' },
  bundoran: { name: 'Bundoran', region: 'Donegal, Ireland', blurb: "A cluster of reef and beach breaks along Ireland's rugged northwest.", lat: 54.4780, lon: -8.2830, offshoreDeg: 90 },
  lacanau: { name: 'Lacanau', region: 'France', blurb: 'A wide, exposed Atlantic beach break and French surf-culture hub.', lat: 44.9810, lon: -1.2030, offshoreDeg: 90 },
  anglet: { name: 'Anglet', region: 'France', blurb: "A string of jettied beach breaks next to Biarritz, France's surf capital.", lat: 43.4930, lon: -1.5280, offshoreDeg: 90 },
  dungeons: { name: 'Dungeons', region: 'Hout Bay, South Africa', blurb: 'A cold, shark-rich big-wave reef reserved for the heaviest South African swells.', lat: -34.0500, lon: 18.3460, offshoreDeg: 45, swellWindow: [200, 250], bestTide: 'all' },
  elandsbay: { name: 'Elands Bay', region: 'Western Cape, South Africa', blurb: 'A long, cold-water left point on a remote stretch of West Coast.', lat: -32.3110, lon: 18.3330, offshoreDeg: 90 },
  padangpadang: { name: 'Padang Padang', region: 'Bali, Indonesia', blurb: 'A short, intense left barrel through a narrow reef slot.', lat: -8.8110, lon: 115.1050, offshoreDeg: 45, swellWindow: [200, 250], bestTide: 'mid' },
  keramas: { name: 'Keramas', region: 'Bali, Indonesia', blurb: 'A fast, punchy right reef break that hosts a world tour event.', lat: -8.5580, lon: 115.3480, offshoreDeg: 0 },
  lakeypeak: { name: 'Lakey Peak', region: 'Sumbawa, Indonesia', blurb: "A powerful A-frame reef peak, one of Sumbawa's best-known waves.", lat: -8.8830, lon: 118.5170, offshoreDeg: 0 },
  lagundribay: { name: 'Lagundri Bay', region: 'Nias, Indonesia', blurb: 'A long, hollow right point inside a horseshoe bay — one of the original Indonesian surf discoveries.', lat: 0.5580, lon: 97.7900, offshoreDeg: 0, swellWindow: [170, 220], bestTide: 'mid' },
  macaronis: { name: 'Macaronis', region: 'Mentawai Islands, Indonesia', blurb: 'A fun, rippable left reef widely rated among the most enjoyable waves on the planet.', lat: -2.7783, lon: 99.9842, offshoreDeg: 90, swellWindow: [180, 230], bestTide: 'all' },
  bellsbeach: { name: 'Bells Beach', region: 'Victoria, Australia', blurb: 'A powerful, historic right point and home to the longest-running pro surf contest.', lat: -38.3690, lon: 144.2830, offshoreDeg: 0, swellWindow: [190, 240], bestTide: 'mid' },
  byronbay: { name: 'The Pass, Byron Bay', region: 'New South Wales, Australia', blurb: 'A long, easy right point wrapping around a lighthouse headland.', lat: -28.6350, lon: 153.6280, offshoreDeg: 250 },
  angourie: { name: 'Angourie', region: 'New South Wales, Australia', blurb: "A classic, sheltered right point — one of Australia's original dedicated surf reserves.", lat: -29.4700, lon: 153.3400, offshoreDeg: 270, swellWindow: [100, 160], bestTide: 'mid' },
  narrabeen: { name: 'North Narrabeen', region: 'Sydney, Australia', blurb: 'A punchy beach break off a rock shelf, a fixture of Sydney competitive surfing.', lat: -33.7180, lon: 151.3020, offshoreDeg: 270 },
  kirra: { name: 'Kirra', region: 'Gold Coast, Australia', blurb: 'Once one of the fastest, longest barrels on Earth off its groyne-fed sandbank.', lat: -28.1670, lon: 153.5330, offshoreDeg: 250, swellWindow: [90, 150], bestTide: 'all' },
  piha: { name: 'Piha', region: 'Auckland, New Zealand', blurb: 'A wild, black-sand beach break beneath dramatic volcanic cliffs.', lat: -36.9530, lon: 174.4700, offshoreDeg: 90 },
  onjuku: { name: 'Onjuku', region: 'Chiba, Japan', blurb: "A consistent beach break close to Tokyo, popular with the city's surfers.", lat: 35.1170, lon: 140.3670, offshoreDeg: 270 },
  hikkaduwa: { name: 'Hikkaduwa', region: 'Sri Lanka', blurb: 'A mellow, reliable reef break inside a lively beach town.', lat: 6.1400, lon: 80.1000, offshoreDeg: 90 },
  weligama: { name: 'Weligama', region: 'Sri Lanka', blurb: "A wide, gentle bay that's become Sri Lanka's top spot to learn.", lat: 5.9730, lon: 80.4290, offshoreDeg: 0 },
  namotu: { name: 'Namotu Left', region: 'Mamanuca Islands, Fiji', blurb: 'A playful reef pass near Cloudbreak, friendlier but still a proper wave.', lat: -17.9330, lon: 177.2170, offshoreDeg: 45 },
  imsouane: { name: 'Imsouane', region: 'Morocco', blurb: "One of the world's longest right points, inside a working fishing bay.", lat: 30.8480, lon: -9.8180, offshoreDeg: 45 },
  tamarin: { name: 'Tamarin', region: 'Mauritius', blurb: 'A powerful left reef break known locally as "the Wall".', lat: -20.3260, lon: 57.3720, offshoreDeg: 90 },
  zarautz: { name: 'Zarautz', region: 'Basque Country, Spain', blurb: "One of Europe's longest beach breaks, a wide bay backed by green hills.", lat: 43.2830, lon: -2.1670, offshoreDeg: 180 },
  croyde: { name: 'Croyde', region: 'Devon, England', blurb: "A punchy, shallow beach break, one of England's best-loved waves.", lat: 51.1290, lon: -4.2350, offshoreDeg: 105 },
  unstad: { name: 'Unstad', region: 'Lofoten, Norway', blurb: 'A dramatic Arctic beach break framed by snow-capped peaks.', lat: 68.2830, lon: 13.0170, offshoreDeg: 90, swellWindow: [290, 350], bestTide: 'all' },
  jungmun: { name: 'Jungmun', region: 'Jeju, South Korea', blurb: "South Korea's best-known beach break, on the island's south coast.", lat: 33.2440, lon: 126.4130, offshoreDeg: 0 },
  riyuebay: { name: 'Riyue Bay', region: 'Hainan, China', blurb: "China's most established surf spot, an exposed point on a resort coastline.", lat: 18.5480, lon: 110.2120, offshoreDeg: 270 },
  jinzun: { name: 'Jinzun', region: 'Taitung, Taiwan', blurb: "Taiwan's premier surf beach, host to an annual international contest.", lat: 22.9500, lon: 121.2350, offshoreDeg: 270 },
  pontadoouro: { name: 'Ponta do Ouro', region: 'Mozambique', blurb: 'An uncrowded point break just north of the South African border.', lat: -26.8500, lon: 32.8830, offshoreDeg: 270 },
  lennoxhead: { name: 'Lennox Head', region: 'New South Wales, Australia', blurb: 'A long, high-performance right point next to a dramatic headland.', lat: -28.7830, lon: 153.6000, offshoreDeg: 270, swellWindow: [100, 160], bestTide: 'mid' },

  // Third batch — added on a second "as many as you can" request, filling in regions the
  // first two batches left thin (US East Coast, Pacific Northwest, Ireland/UK, West Africa,
  // remote Australia, cold-water Atlantic). Same caveat as both earlier batches: reasonable
  // estimates from available sources, not surveyed. The remote/lesser-documented entries in
  // this batch (Todos Santos, Nihiwatu, Bawa, Wai'ao, Pasta Point, One Eye, Shipstern Bluff,
  // Sandvík, Lawrencetown, Cactus Beach) are lower-confidence than the rest -- built-in spots
  // known well enough to describe but without a precisely published coordinate double-checked.
  huntingtonbeach: { name: 'Huntington Beach', region: 'California, USA', blurb: '"Surf City USA" — long stretches of consistent, contest-friendly beach break peaks.', lat: 33.6553, lon: -118.0053, offshoreDeg: 45 },
  oceanbeachsf: { name: 'Ocean Beach', region: 'San Francisco, California, USA', blurb: 'Powerful, shifting beach break with strong currents and serious big-wave days.', lat: 37.7594, lon: -122.5107, offshoreDeg: 90 },
  swamis: { name: "Swami's", region: 'Encinitas, California, USA', blurb: 'A reliable, well-organized reef point popular with SoCal locals.', lat: 33.0281, lon: -117.2934, offshoreDeg: 60 },
  rockawaybeach: { name: 'Rockaway Beach', region: 'Queens, New York, USA', blurb: "New York City's home beach break, best in the fall and winter groundswell season.", lat: 40.5795, lon: -73.8351, offshoreDeg: 0 },
  capehatteras: { name: 'Cape Hatteras', region: 'Outer Banks, North Carolina, USA', blurb: 'Exposed Atlantic beach breaks that pick up nearly every hurricane swell.', lat: 35.2496, lon: -75.5284, offshoreDeg: 270 },
  follybeach: { name: 'Folly Beach', region: 'South Carolina, USA', blurb: "The Lowcountry's best-known beach break, a short drive from Charleston.", lat: 32.6551, lon: -79.9403, offshoreDeg: 315 },
  newsmyrnabeach: { name: 'New Smyrna Beach', region: 'Florida, USA', blurb: 'A consistent inlet beach break, notorious for its shark population.', lat: 29.0258, lon: -80.9270, offshoreDeg: 270 },
  peahi: { name: "Jaws (Pe'ahi)", region: 'Maui, Hawaii, USA', blurb: 'One of the biggest tow-in and paddle waves on Earth when a big NW swell hits.', lat: 20.9330, lon: -156.3140, offshoreDeg: 180 },
  alamoana: { name: 'Ala Moana Bowls', region: 'Oahu, Hawaii, USA', blurb: "A hollow, high-performance reef right just off Honolulu's south shore.", lat: 21.2830, lon: -157.8580, offshoreDeg: 0 },
  hanalei: { name: 'Hanalei Bay', region: 'Kauai, Hawaii, USA', blurb: 'A scenic, sheltered bay with gentle summer waves and a serious winter pier break.', lat: 22.2050, lon: -159.5000, offshoreDeg: 180 },
  shortsands: { name: 'Short Sands', region: 'Oregon, USA', blurb: 'A sheltered cove break in Oswald West State Park, a Pacific Northwest favorite.', lat: 45.7520, lon: -123.9700, offshoreDeg: 90 },
  westport: { name: 'Westport', region: 'Washington, USA', blurb: "A cold, powerful jetty break, one of the Pacific Northwest's most consistent spots.", lat: 46.9010, lon: -124.1450, offshoreDeg: 90 },
  todossantos: { name: 'Killers (Todos Santos)', region: 'Ensenada, Baja California, Mexico', blurb: 'A big-wave reef off an island, one of the heaviest waves in North America.', lat: 31.8300, lon: -116.7280, offshoreDeg: 90 },
  laticla: { name: 'La Ticla', region: 'Michoacán, Mexico', blurb: 'A long, hollow left point on a wild, largely undeveloped stretch of coast.', lat: 18.6060, lon: -103.6650, offshoreDeg: 45 },
  puntamita: { name: 'Punta Mita', region: 'Nayarit, Mexico', blurb: 'A gentle, long right point popular with longboarders in the Riviera Nayarit.', lat: 20.7730, lon: -105.5330, offshoreDeg: 90 },
  tamarindo: { name: 'Tamarindo', region: 'Guanacaste, Costa Rica', blurb: 'An easygoing beach and river-mouth break at the heart of a busy surf town.', lat: 10.2990, lon: -85.8370, offshoreDeg: 90 },
  dominical: { name: 'Dominical', region: 'Costa Rica', blurb: 'A powerful, punchy beach break on the jungle-backed southern Pacific coast.', lat: 9.2480, lon: -83.8620, offshoreDeg: 60 },
  venao: { name: 'Playa Venao', region: 'Panama', blurb: 'A crescent-shaped bay with consistent peaks on both ends, a backpacker surf hub.', lat: 7.4180, lon: -80.1980, offshoreDeg: 0 },
  playacolorado: { name: 'Playa Colorado', region: 'Nicaragua', blurb: 'A punchy, hollow right reef point popular with Central American surf camps.', lat: 11.7940, lon: -86.1940, offshoreDeg: 50 },
  cabarete: { name: 'Cabarete (Encuentro)', region: 'Dominican Republic', blurb: "The Caribbean's best-known surf town, with reefs and beach breaks for every level.", lat: 19.7580, lon: -70.4250, offshoreDeg: 180 },
  lawrencetown: { name: 'Lawrencetown Beach', region: 'Nova Scotia, Canada', blurb: "Atlantic Canada's best-known cold-water beach break.", lat: 44.6430, lon: -63.3860, offshoreDeg: 0 },
  pichilemu: { name: 'Pichilemu', region: 'Chile', blurb: "Chile's surf capital, with a long, rippable left point next to town.", lat: -34.3890, lon: -72.0010, offshoreDeg: 90 },
  arica: { name: 'El Gringo', region: 'Arica, Chile', blurb: "A powerful left point in Chile's far north, close to the Peruvian border.", lat: -18.4780, lon: -70.3210, offshoreDeg: 90 },
  montanita: { name: 'Montañita', region: 'Ecuador', blurb: "Ecuador's best-known surf town, with a lively beach and point break out front.", lat: -1.8330, lon: -80.7420, offshoreDeg: 90 },
  maresias: { name: 'Maresias', region: 'São Paulo, Brazil', blurb: "One of Brazil's best-known beach breaks, on a scenic bay near São Sebastião.", lat: -23.7960, lon: -45.5670, offshoreDeg: 10 },
  lapaloma: { name: 'La Paloma', region: 'Rocha, Uruguay', blurb: "Uruguay's low-key surf town, with reef and beach breaks scattered along the point.", lat: -34.6650, lon: -54.1500, offshoreDeg: 315 },
  watergatebay: { name: 'Watergate Bay', region: 'Cornwall, England', blurb: 'A wide, sandy Atlantic beach break popular with Cornish surf schools.', lat: 50.4420, lon: -5.0550, offshoreDeg: 135 },
  porthleven: { name: 'Porthleven', region: 'Cornwall, England', blurb: 'A shallow, powerful reef break beside a historic harbor wall.', lat: 50.0850, lon: -5.3160, offshoreDeg: 0 },
  rhossili: { name: 'Rhossili Bay', region: 'Gower, Wales', blurb: 'A dramatic three-mile beach break backed by cliffs and green hills.', lat: 51.5680, lon: -4.2930, offshoreDeg: 90 },
  lahinch: { name: 'Lahinch', region: 'County Clare, Ireland', blurb: "A consistent beach break beneath the Cliffs of Moher, Ireland's original surf town.", lat: 52.9330, lon: -9.3450, offshoreDeg: 90 },
  mullaghmore: { name: 'Mullaghmore Head', region: 'County Sligo, Ireland', blurb: 'A frigid, ferocious big-wave reef, among the heaviest waves in Europe.', lat: 54.4680, lon: -8.4470, offshoreDeg: 135, swellWindow: [270, 320], bestTide: 'all' },
  biarritz: { name: 'Côte des Basques', region: 'Biarritz, France', blurb: 'A classic beach break beneath Biarritz, birthplace of European surfing.', lat: 43.4780, lon: -1.5660, offshoreDeg: 90 },
  somo: { name: 'Somo', region: 'Cantabria, Spain', blurb: 'A wide, sandy beach break across the bay from Santander.', lat: 43.4610, lon: -3.7440, offshoreDeg: 180 },
  carcavelos: { name: 'Carcavelos', region: 'Lisbon, Portugal', blurb: "Lisbon's most popular beach break, with a heavier reef at its northern end.", lat: 38.6800, lon: -9.3350, offshoreDeg: 30 },
  sandvik: { name: 'Sandvík', region: 'Reykjanes Peninsula, Iceland', blurb: 'A cold, moody beach break beneath volcanic cliffs, for the hardiest surfers.', lat: 63.8320, lon: -22.6980, offshoreDeg: 0 },
  hashpoint: { name: 'Hash Point', region: 'Taghazout, Morocco', blurb: 'A long right point in a laid-back fishing village turned surf destination.', lat: 30.5460, lon: -9.7100, offshoreDeg: 90 },
  ngor: { name: 'Ngor Right', region: 'Dakar, Senegal', blurb: "West Africa's best-known wave, a reef right off a small island village.", lat: 14.7460, lon: -17.5170, offshoreDeg: 90 },
  caverock: { name: 'Cave Rock', region: 'Durban, South Africa', blurb: "A punchy right reef at the entrance to Durban's harbor.", lat: -29.9130, lon: 31.0430, offshoreDeg: 270 },
  canggu: { name: 'Canggu (Batu Bolong)', region: 'Bali, Indonesia', blurb: "A lively reef break at the heart of Bali's surf-town scene.", lat: -8.6560, lon: 115.1330, offshoreDeg: 50 },
  nihiwatu: { name: "Nihiwatu (Occy's Left)", region: 'Sumba, Indonesia', blurb: 'A long, world-class left reef fronting a famous luxury resort.', lat: -9.6890, lon: 119.2870, offshoreDeg: 50 },
  bawa: { name: 'Bawa', region: 'Hinako Islands, Indonesia', blurb: 'A remote, near-perfect left barrel wrapping around a tiny island.', lat: 0.7500, lon: 97.1170, offshoreDeg: 50 },
  launion: { name: 'La Union', region: 'Philippines', blurb: "The Philippines' most popular surf town, with easygoing beach-break peaks.", lat: 16.6660, lon: 120.3130, offshoreDeg: 90 },
  miyazaki: { name: 'Kisakihama', region: 'Miyazaki, Japan', blurb: "One of Japan's best-known beach breaks, on the subtropical Kyushu coast.", lat: 31.9520, lon: 131.4590, offshoreDeg: 270 },
  midigama: { name: 'Midigama', region: 'Sri Lanka', blurb: 'A pair of reef breaks on the south coast, a step up from nearby Weligama.', lat: 5.9660, lon: 80.3960, offshoreDeg: 0 },
  waao: { name: "Wai'ao", region: 'Yilan, Taiwan', blurb: "Taiwan's most popular beach break, a short drive from Taipei.", lat: 24.8610, lon: 121.8580, offshoreDeg: 270 },
  pastapoint: { name: 'Pasta Point', region: 'Thulusdhoo, Maldives', blurb: 'A soft, playful left reef inside a resort-run atoll break.', lat: 4.3760, lon: 73.6440, offshoreDeg: 90 },
  oneeye: { name: 'One Eye', region: 'Le Morne, Mauritius', blurb: 'A world-class left reef breaking beneath a dramatic basalt mountain.', lat: -20.4560, lon: 57.3120, offshoreDeg: 90 },
  noosaheads: { name: 'Noosa Heads', region: 'Queensland, Australia', blurb: 'A string of gentle, scenic points inside a national park headland.', lat: -26.3980, lon: 153.0990, offshoreDeg: 225, swellWindow: [40, 100], bestTide: 'all' },
  burleighheads: { name: 'Burleigh Heads', region: 'Gold Coast, Australia', blurb: 'A fast, sand-bottomed point next to a rocky headland, near the Superbank.', lat: -28.0930, lon: 153.4470, offshoreDeg: 250 },
  shipsternbluff: { name: 'Shipstern Bluff', region: 'Tasmania, Australia', blurb: 'A freakish, ledging slab beneath towering sea cliffs — as heavy as it looks.', lat: -43.1670, lon: 147.9330, offshoreDeg: 345, swellWindow: [170, 220], bestTide: 'all' },
  thebox: { name: 'The Box', region: 'Gracetown, Western Australia', blurb: 'A short, ultra-heavy slab that breaks in shallow water close to the rocks.', lat: -33.8580, lon: 114.9980, offshoreDeg: 90, swellWindow: [200, 250], bestTide: 'low' },
  cactus: { name: 'Cactus Beach', region: 'South Australia', blurb: 'A remote, wind-blasted cluster of world-class reefs on the Great Australian Bight.', lat: -32.0330, lon: 133.6330, offshoreDeg: 350 },
  restaurants: { name: 'Restaurants', region: 'Tavarua, Fiji', blurb: "Cloudbreak's playful neighbor, a lighter left reef inside the same reef pass.", lat: -17.8390, lon: 177.1890, offshoreDeg: 50 },
  shipwreckbay: { name: 'Shipwreck Bay', region: 'Ahipara, New Zealand', blurb: 'A long left point at the southern end of Ninety Mile Beach.', lat: -35.1670, lon: 173.1330, offshoreDeg: 90, swellWindow: [230, 290], bestTide: 'mid' },
  // Fourth batch. Well-known breaks filling out coverage that the first three left thin:
  // the US East Coast, northern Europe and the North Sea, the Australian city beaches,
  // New Zealand's South Island, and more of Indonesia and Central America. Coordinates
  // place each break to within a few hundred metres, which is what the globe and the
  // directions link need; they are not surveyed line-ups.
  sunsetcliffs: { name: 'Sunset Cliffs', region: 'San Diego, CA', blurb: 'Reefs tucked under the cliffs, best on a mid tide with a west swell running.', lat: 32.7157, lon: -117.2547, offshoreDeg: 90 },
  sanonofre: { name: 'San Onofre', region: 'San Clemente, CA', blurb: 'Mellow, forgiving cobblestone peaks — the classic longboard wave of Southern California.', lat: 33.3733, lon: -117.5656, offshoreDeg: 60 },
  cardiffreef: { name: 'Cardiff Reef', region: 'Cardiff-by-the-Sea, CA', blurb: 'Consistent reef peak that works through the tides, and takes a crowd well.', lat: 33.017, lon: -117.281, offshoreDeg: 90 },
  oceansidepier: { name: 'Oceanside Pier', region: 'Oceanside, CA', blurb: 'Sandbar peaks either side of the pier, punchy on a solid west swell.', lat: 33.193, lon: -117.386, offshoreDeg: 90 },
  venturapoint: { name: 'Ventura Point', region: 'Ventura, CA', blurb: 'Long right-hand cobblestone point that lines up for hundreds of yards on a winter swell.', lat: 34.276, lon: -119.301, offshoreDeg: 20 },
  countyline: { name: 'County Line', region: 'Malibu, CA', blurb: 'Open beach and reef peaks at the county border, reliable when Malibu is flat.', lat: 34.047, lon: -118.92, offshoreDeg: 20 },
  pleasurepoint: { name: 'Pleasure Point', region: 'Santa Cruz, CA', blurb: 'A string of right-hand reef sections along the cliff, cold and consistently good.', lat: 36.956, lon: -121.972, offshoreDeg: 20 },
  lindamar: { name: 'Linda Mar', region: 'Pacifica, CA', blurb: "Forgiving beach break just south of San Francisco, the Bay Area's learn-to-surf beach.", lat: 37.596, lon: -122.506, offshoreDeg: 90 },
  windansea: { name: 'Windansea', region: 'La Jolla, CA', blurb: 'Powerful, shifting reef peaks below the palm shack. Localised and worth the respect.', lat: 32.828, lon: -117.28, offshoreDeg: 90 },
  elporto: { name: 'El Porto', region: 'Manhattan Beach, CA', blurb: 'The most consistent beach break in the South Bay, punchy on a combo swell.', lat: 33.902, lon: -118.418, offshoreDeg: 70 },
  zuma: { name: 'Zuma Beach', region: 'Malibu, CA', blurb: 'Wide-open beach break that picks up far more swell than the points nearby.', lat: 34.018, lon: -118.821, offshoreDeg: 20 },
  sebastianinlet: { name: 'Sebastian Inlet', region: 'Florida, USA', blurb: "The East Coast's proving ground — a wedging right off the jetty when a swell shows.", lat: 27.86, lon: -80.447, offshoreDeg: 270 },
  cocoabeach: { name: 'Cocoa Beach', region: 'Florida, USA', blurb: 'Small, friendly beach break that produced more than its share of champions.', lat: 28.36, lon: -80.607, offshoreDeg: 270 },
  wrightsville: { name: 'Wrightsville Beach', region: 'North Carolina, USA', blurb: 'Consistent sandbars and a jetty, best on a hurricane swell in late summer.', lat: 34.21, lon: -77.796, offshoreDeg: 270 },
  virginiabeach: { name: 'Virginia Beach', region: 'Virginia, USA', blurb: 'Long stretch of beach break peaks, at their best on an autumn groundswell.', lat: 36.833, lon: -75.968, offshoreDeg: 270 },
  longbeachny: { name: 'Long Beach', region: 'New York, USA', blurb: 'Jetty-lined sandbars a train ride from Manhattan, firing on a hurricane swell.', lat: 40.583, lon: -73.658, offshoreDeg: 340 },
  narragansett: { name: 'Narragansett', region: 'Rhode Island, USA', blurb: "New England's most reliable beach break, and freezing outside of summer.", lat: 41.431, lon: -71.455, offshoreDeg: 340 },
  manasquan: { name: 'Manasquan Inlet', region: 'New Jersey, USA', blurb: 'Sand-bottom peaks beside the inlet jetty, punchy on a tight-period swell.', lat: 40.103, lon: -74.033, offshoreDeg: 290 },
  jaws: { name: 'Peʻahi (Jaws)', region: 'Maui, Hawaii', blurb: 'The most famous big-wave tow and paddle arena on Earth, breaking on an outer reef.', lat: 20.943, lon: -156.302, offshoreDeg: 200, swellWindow: [300, 350], bestTide: 'all' },
  rockypoint: { name: 'Rocky Point', region: 'Oahu, Hawaii', blurb: "Shifting North Shore peaks, lefts and rights, and the shore's busiest performance wave.", lat: 21.662, lon: -158.043, offshoreDeg: 200 },
  queens: { name: 'Queens', region: 'Waikiki, Hawaii', blurb: 'Gentle rolling reef wave in front of Waikiki, where surfing was reintroduced to the world.', lat: 21.272, lon: -157.824, offshoreDeg: 20 },
  makaha: { name: 'Makaha', region: 'Oahu, Hawaii', blurb: 'Historic west-side point with a big, bowling wall and deep local roots.', lat: 21.477, lon: -158.22, offshoreDeg: 70 },
  scorpionbay: { name: 'Scorpion Bay', region: 'Baja California Sur, Mexico', blurb: 'Seven right-hand points that link on a big south swell, in the middle of nowhere.', lat: 26.256, lon: -112.477, offshoreDeg: 70 },
  sanmiguel: { name: 'San Miguel', region: 'Ensenada, Mexico', blurb: 'Cobblestone right point just south of the border, best on a solid winter northwest.', lat: 31.9, lon: -116.766, offshoreDeg: 70 },
  troncones: { name: 'Troncones', region: 'Guerrero, Mexico', blurb: 'Long sandy beach with a point at each end, and warm water year-round.', lat: 17.783, lon: -101.733, offshoreDeg: 20 },
  elzonte: { name: 'El Zonte', region: 'La Libertad, El Salvador', blurb: 'Cobblestone right point that put this stretch of coast on the map.', lat: 13.495, lon: -89.44, offshoreDeg: 20 },
  lasflores: { name: 'Las Flores', region: 'La Unión, El Salvador', blurb: 'Machine-like right point peeling over cobblestones into a palm-lined bay.', lat: 13.174, lon: -88.033, offshoreDeg: 20 },
  olliespoint: { name: "Ollie's Point", region: 'Guanacaste, Costa Rica', blurb: 'Long, walling right point in a remote bay north of Tamarindo.', lat: 10.9, lon: -85.75, offshoreDeg: 70 },
  nosara: { name: 'Playa Guiones', region: 'Nosara, Costa Rica', blurb: 'Dependable beach break peaks along a long, protected stretch of sand.', lat: 9.953, lon: -85.68, offshoreDeg: 70 },
  bocasbluff: { name: 'Playa Bluff', region: 'Bocas del Toro, Panama', blurb: 'Heavy Caribbean beach break barrel that turns on in the winter months.', lat: 9.35, lon: -82.233, offshoreDeg: 250 },
  lobitos: { name: 'Lobitos', region: 'Piura, Peru', blurb: 'Cold, mechanical left points down a desert oil-town coastline.', lat: -4.452, lon: -81.281, offshoreDeg: 110, swellWindow: [190, 240], bestTide: 'all' },
  iquique: { name: 'Playa Cavancha', region: 'Iquique, Chile', blurb: 'Punchy urban reef and beach peaks in the driest desert on Earth.', lat: -20.228, lon: -70.149, offshoreDeg: 90 },
  matanzas: { name: 'Matanzas', region: "O'Higgins, Chile", blurb: 'Long left point and beach break in a windy bay south of Santiago.', lat: -33.96, lon: -71.872, offshoreDeg: 90 },
  saquarema: { name: 'Saquarema', region: 'Rio de Janeiro, Brazil', blurb: "Brazil's most powerful beach break, and a fixture on the world tour.", lat: -22.934, lon: -42.489, offshoreDeg: 340 },
  noronha: { name: 'Cacimba do Padre', region: 'Fernando de Noronha, Brazil', blurb: 'Barrelling beach break beneath two volcanic peaks, on a remote Atlantic island.', lat: -3.854, lon: -32.436, offshoreDeg: 110 },
  praiadorosa: { name: 'Praia do Rosa', region: 'Santa Catarina, Brazil', blurb: 'Beach break in a horseshoe bay backed by green hills and lagoons.', lat: -28.133, lon: -48.64, offshoreDeg: 290 },
  guincho: { name: 'Praia do Guincho', region: 'Cascais, Portugal', blurb: 'Wild, wind-exposed Atlantic beach break under the Sintra hills.', lat: 38.733, lon: -9.472, offshoreDeg: 90 },
  sagres: { name: 'Praia do Tonel', region: 'Sagres, Portugal', blurb: 'Exposed corner at the southwest tip of Europe, catching swell when everywhere else is flat.', lat: 37.0, lon: -8.945, offshoreDeg: 20 },
  pantin: { name: 'Praia de Pantín', region: 'Galicia, Spain', blurb: 'Consistent, punchy beach break on the wild Galician coast.', lat: 43.63, lon: -8.113, offshoreDeg: 180 },
  rodiles: { name: 'Rodiles', region: 'Asturias, Spain', blurb: 'A celebrated left river-mouth wave that peels along a sandbar beside a pine forest.', lat: 43.533, lon: -5.383, offshoreDeg: 180 },
  capbreton: { name: 'La Piste', region: 'Capbreton, France', blurb: 'Heavy, hollow sandbank barrels beside the blockhaus.', lat: 43.642, lon: -1.445, offshoreDeg: 90 },
  easkey: { name: 'Easkey', region: 'Sligo, Ireland', blurb: 'Reliable reef lefts and rights below a ruined castle on the wild Atlantic coast.', lat: 54.287, lon: -8.96, offshoreDeg: 180 },
  porthcawl: { name: 'Rest Bay', region: 'Porthcawl, Wales', blurb: "South Wales' most consistent beach break, working through most of the tide.", lat: 51.489, lon: -3.713, offshoreDeg: 20 },
  saltburn: { name: 'Saltburn', region: 'North Yorkshire, England', blurb: 'A north-east England beach and pier break, cold and surprisingly consistent.', lat: 54.583, lon: -0.97, offshoreDeg: 290 },
  scheveningen: { name: 'Scheveningen', region: 'The Hague, Netherlands', blurb: 'Short-period North Sea beach break, busy whenever a blow puts swell in the water.', lat: 52.108, lon: 4.275, offshoreDeg: 110 },
  sylt: { name: 'Sylt', region: 'Germany', blurb: "Germany's surf capital — a long North Sea sandbar coast on a windswept island.", lat: 54.9, lon: 8.3, offshoreDeg: 110 },
  klitmoller: { name: 'Klitmøller', region: 'Denmark', blurb: 'Known as Cold Hawaii: a reef and point setup on the Danish North Sea coast.', lat: 57.04, lon: 8.48, offshoreDeg: 110, swellWindow: [280, 340], bestTide: 'all' },
  hoddevik: { name: 'Hoddevik', region: 'Norway', blurb: 'A sand-bottom bay ringed by cliffs, surfed under the midnight sun and the northern lights.', lat: 62.033, lon: 5.1, offshoreDeg: 110, swellWindow: [280, 330], bestTide: 'all' },
  killerpoint: { name: 'Killer Point', region: 'Taghazout, Morocco', blurb: 'The longest and most powerful of the Taghazout points, named for the passing whales.', lat: 30.554, lon: -9.718, offshoreDeg: 70 },
  safi: { name: 'Safi', region: 'Morocco', blurb: 'A world-class right point that barrels down the reef when a big northwest lands.', lat: 32.28, lon: -9.25, offshoreDeg: 70 },
  dakhla: { name: 'Dakhla', region: 'Western Sahara', blurb: 'Desert right points wrapping into a huge lagoon, windy and near-empty.', lat: 23.71, lon: -15.94, offshoreDeg: 70 },
  sealpoint: { name: 'Seal Point', region: 'Cape St Francis, South Africa', blurb: 'Long, ruler-edged right point immortalised in The Endless Summer.', lat: -34.21, lon: 24.838, offshoreDeg: 340, swellWindow: [190, 240], bestTide: 'all' },
  muizenberg: { name: 'Muizenberg', region: 'Cape Town, South Africa', blurb: 'Gentle, sandy corner of False Bay where most of Cape Town learns to surf.', lat: -34.108, lon: 18.47, offshoreDeg: 340 },
  newpier: { name: 'New Pier', region: 'Durban, South Africa', blurb: 'Sand-bottom peaks between the piers, the heart of South African surfing.', lat: -29.858, lon: 31.04, offshoreDeg: 250 },
  tofo: { name: 'Tofo', region: 'Inhambane, Mozambique', blurb: 'Warm-water points and beach break beside a bay known for manta rays.', lat: -23.85, lon: 35.54, offshoreDeg: 250 },
  hiltonbeach: { name: 'Hilton Beach', region: 'Tel Aviv, Israel', blurb: "The city's best-known break, crowded whenever a Mediterranean windswell arrives.", lat: 32.087, lon: 34.768, offshoreDeg: 110, swellWindow: [240, 330], bestTide: 'all' },
  hollowtrees: { name: 'Hollow Trees', region: 'Mentawai Islands, Indonesia', blurb: 'A perfect, shallow right-hand reef barrel — one of the best waves in the world.', lat: -2.117, lon: 99.567, offshoreDeg: 70, swellWindow: [180, 230], bestTide: 'mid' },
  bingin: { name: 'Bingin', region: 'Bali, Indonesia', blurb: 'Short, intense left reef barrel below a cliff of stacked guesthouses.', lat: -8.808, lon: 115.113, offshoreDeg: 50, swellWindow: [200, 250], bestTide: 'low' },
  medewi: { name: 'Medewi', region: 'Bali, Indonesia', blurb: "A long, slow left point on Bali's quiet west coast, ideal on a longboard.", lat: -8.42, lon: 114.81, offshoreDeg: 50 },
  tland: { name: 'T-Land', region: 'Rote, Indonesia', blurb: 'A long, mellow left reef wave in a remote bay off Timor.', lat: -10.9, lon: 122.83, offshoreDeg: 20 },
  krui: { name: 'Ujung Bocur', region: 'Krui, Indonesia', blurb: "Consistent left reef point on Sumatra's swell-soaked west coast.", lat: -5.24, lon: 103.92, offshoreDeg: 70 },
  kata: { name: 'Kata Beach', region: 'Phuket, Thailand', blurb: "Thailand's best-known beach break, working through the southwest monsoon.", lat: 7.818, lon: 98.297, offshoreDeg: 70 },
  ikumi: { name: 'Ikumi Beach', region: 'Tokushima, Japan', blurb: "One of Japan's most consistent beach breaks, best on a typhoon swell.", lat: 33.548, lon: 134.283, offshoreDeg: 290 },
  baler: { name: 'Sabang Beach', region: 'Baler, Philippines', blurb: 'Where Apocalypse Now brought surfing to the Philippines — a gentle beach break.', lat: 15.758, lon: 121.563, offshoreDeg: 250 },
  chickens: { name: 'Chickens', region: 'North Malé Atoll, Maldives', blurb: 'A long, wrapping left reef pass over shallow coral in warm, clear water.', lat: 4.287, lon: 73.39, offshoreDeg: 70 },
  winkipop: { name: 'Winkipop', region: 'Victoria, Australia', blurb: 'The fast, racy right next door to Bells, and the better wave when it is on.', lat: -38.369, lon: 144.279, offshoreDeg: 340, swellWindow: [190, 240], bestTide: 'mid' },
  crescenthead: { name: 'Crescent Head', region: 'New South Wales, Australia', blurb: 'A long, sloping right point that is spiritual home to Australian longboarding.', lat: -31.188, lon: 152.98, offshoreDeg: 250, swellWindow: [100, 160], bestTide: 'all' },
  duranbah: { name: 'Duranbah', region: 'New South Wales, Australia', blurb: 'Punchy beach break beside the Tweed river mouth, the most surfed sand in the country.', lat: -28.166, lon: 153.551, offshoreDeg: 250, swellWindow: [80, 150], bestTide: 'all' },
  maroubra: { name: 'Maroubra', region: 'Sydney, Australia', blurb: "Sydney's heaviest beach break, with a fierce local scene to match.", lat: -33.95, lon: 151.256, offshoreDeg: 250 },
  bondi: { name: 'Bondi Beach', region: 'Sydney, Australia', blurb: 'The most famous beach in Australia — shifting sandbars and a permanent crowd.', lat: -33.891, lon: 151.277, offshoreDeg: 250 },
  manly: { name: 'Manly Beach', region: 'Sydney, Australia', blurb: 'Where Australian surfing began in 1915, and still a reliable beach break.', lat: -33.796, lon: 151.288, offshoreDeg: 250 },
  gnaraloo: { name: 'Gnaraloo', region: 'Western Australia', blurb: 'Tombstones — a heavy, remote left reef at the edge of a station on the Ningaloo coast.', lat: -23.79, lon: 113.51, offshoreDeg: 110, swellWindow: [200, 250], bestTide: 'all' },
  redbluff: { name: 'Red Bluff', region: 'Western Australia', blurb: 'A big, hollow left point below red cliffs, camped on rather than driven to.', lat: -24.02, lon: 113.4, offshoreDeg: 110 },
  yallingup: { name: 'Yallingup', region: 'Western Australia', blurb: 'Long, powerful reef and point wave at the top of the Margaret River region.', lat: -33.642, lon: 114.988, offshoreDeg: 110 },
  stclair: { name: 'St Clair Beach', region: 'Dunedin, New Zealand', blurb: 'Cold, consistent beach break at the bottom of the South Island.', lat: -45.911, lon: 170.487, offshoreDeg: 290 },
  makorori: { name: 'Makorori', region: 'Gisborne, New Zealand', blurb: 'A run of points and beach breaks just north of the first city to see the sun.', lat: -38.63, lon: 178.08, offshoreDeg: 250 },
  fitzroybeach: { name: 'Fitzroy Beach', region: 'New Plymouth, New Zealand', blurb: 'Black-sand beach break under the cone of Mount Taranaki.', lat: -39.048, lon: 174.09, offshoreDeg: 110 },
  // Fifth batch: the Israeli Mediterranean coast, north to south. The coastline runs roughly
  // north-south facing west, so offshore is easterly and the swell window is the western arc.
  // `bestTide` is 'all' throughout because the eastern Mediterranean is close to tideless here
  // (a range of roughly 30-40cm) — claiming a tide preference would be inventing a signal.
  nahariya: { name: 'Nahariya', region: 'Northern District, Israel', blurb: 'Northern beach break that picks up the most swell on a winter northwesterly.', lat: 33.005, lon: 35.09, offshoreDeg: 100, swellWindow: [250, 330], bestTide: 'all' },
  akko: { name: 'Akko', region: 'Northern District, Israel', blurb: 'Sheltered break under the old city walls, working when the north swell wraps in.', lat: 32.925, lon: 35.065, offshoreDeg: 100, swellWindow: [260, 340], bestTide: 'all' },
  batgalim: { name: 'Bat Galim', region: 'Haifa, Israel', blurb: "Haifa's home break, tucked beside the breakwater and best on a west swell.", lat: 32.832, lon: 34.985, offshoreDeg: 100, swellWindow: [250, 330], bestTide: 'all' },
  atlit: { name: 'Atlit', region: 'Haifa District, Israel', blurb: 'Reef and beach peaks below the Crusader fortress, quieter than the city breaks.', lat: 32.69, lon: 34.936, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  habonim: { name: 'Habonim', region: 'Haifa District, Israel', blurb: 'Rocky coves and sandbars along a protected nature reserve shoreline.', lat: 32.637, lon: 34.925, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  nahsholim: { name: 'Nahsholim', region: 'Haifa District, Israel', blurb: 'Sandy bay beside Tel Dor, gentle and good for longer boards.', lat: 32.611, lon: 34.918, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  beithanania: { name: 'Beit Hanania', region: 'Haifa District, Israel', blurb: 'Open beach break north of Caesarea that handles more size than most.', lat: 32.545, lon: 34.912, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  michmoret: { name: 'Michmoret', region: 'Central District, Israel', blurb: 'Long sandy stretch with a jetty, one of the most consistent spots on the coast.', lat: 32.404, lon: 34.869, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  beityanai: { name: 'Beit Yanai', region: 'Central District, Israel', blurb: 'Punchy beach break under the cliffs, a favourite when a westerly fills in.', lat: 32.383, lon: 34.869, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  sironit: { name: 'Sironit', region: 'Netanya, Israel', blurb: "Netanya's main beach, sheltered by the cliff and busy whenever it breaks.", lat: 32.336, lon: 34.85, offshoreDeg: 100, swellWindow: [250, 330], bestTide: 'all' },
  poleg: { name: 'Poleg', region: 'Netanya, Israel', blurb: 'Sandbars at the river mouth south of Netanya, best on a clean west swell.', lat: 32.293, lon: 34.843, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  herzliya: { name: 'Acadia', region: 'Herzliya, Israel', blurb: "Herzliya's best-known peak, and one of the more competitive line-ups in Israel.", lat: 32.163, lon: 34.797, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  maravi: { name: 'Maravi', region: 'Tel Aviv, Israel', blurb: 'Tel Aviv beach break just north of the marina, crowded on any decent morning.', lat: 32.093, lon: 34.771, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  bananabeach: { name: 'Banana Beach', region: 'Tel Aviv, Israel', blurb: "Central Tel Aviv sandbars, mellow and the city's usual first surf.", lat: 32.07, lon: 34.762, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  batyam: { name: 'Bat Yam', region: 'Tel Aviv District, Israel', blurb: 'Breakwater-sheltered peaks just south of Tel Aviv, cleaner in a south wind.', lat: 32.017, lon: 34.74, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  palmachim: { name: 'Palmachim', region: 'Central District, Israel', blurb: 'Open, uncrowded beach break beside the kibbutz and the river mouth.', lat: 31.93, lon: 34.7, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  ashdod: { name: 'Ashdod', region: 'Southern District, Israel', blurb: 'Port-side sandbars that turn on when a winter storm tracks down the coast.', lat: 31.826, lon: 34.635, offshoreDeg: 100, swellWindow: [240, 330], bestTide: 'all' },
  ashkelon: { name: 'Ashkelon', region: 'Southern District, Israel', blurb: 'The southernmost consistent break, exposed to swell from the west and south-west.', lat: 31.678, lon: 34.554, offshoreDeg: 100, swellWindow: [230, 320], bestTide: 'all' },
};
export const ORDER = ['trestles', 'blacks', 'rincon', 'wedge', 'pipeline', 'teahupoo', 'jbay', 'uluwatu', 'snapper', 'nazare', 'chicama', 'raglan', 'puertoescondido', 'hossegor', 'mundaka', 'cloudbreak', 'skeletonbay', 'pavones', 'fistral', 'anchorpoint', 'margaretriver', 'montauk', 'arugambay', 'gland', 'siargao', 'ericeira', 'desertpoint', 'tofino', 'joaquina', 'puntadelobos', 'shonan', 'kovalam', 'caesarea', 'elcotillo', 'popoyo', 'santacatalina', 'deadmans', 'muine', 'laentrada', 'montoya', 'darne', 'capesolander', 'masnou', 'capomarina',
  'malibu', 'steamerlane', 'mavericks', 'waimeabay', 'sunsetbeach', 'honoluabay', 'hookipa', 'sayulita', 'barradelacruz', 'playahermosa', 'witchsrock', 'salsabrava', 'elsunzal', 'puntaroca', 'picoalto', 'mancora', 'guardadoembau', 'itacare', 'rinconpr', 'soupbowl', 'lasanta', 'elconfital', 'supertubos', 'amado', 'thursoeast', 'bundoran', 'lacanau', 'anglet', 'dungeons', 'elandsbay', 'padangpadang', 'keramas', 'lakeypeak', 'lagundribay', 'macaronis', 'bellsbeach', 'byronbay', 'angourie', 'narrabeen', 'kirra', 'piha', 'onjuku', 'hikkaduwa', 'weligama', 'namotu', 'imsouane', 'tamarin', 'zarautz', 'croyde', 'unstad', 'jungmun', 'riyuebay', 'jinzun', 'pontadoouro', 'lennoxhead',
  'huntingtonbeach', 'oceanbeachsf', 'swamis', 'rockawaybeach', 'capehatteras', 'follybeach', 'newsmyrnabeach', 'peahi', 'alamoana', 'hanalei', 'shortsands', 'westport', 'todossantos', 'laticla', 'puntamita', 'tamarindo', 'dominical', 'venao', 'playacolorado', 'cabarete', 'lawrencetown', 'pichilemu', 'arica', 'montanita', 'maresias', 'lapaloma', 'watergatebay', 'porthleven', 'rhossili', 'lahinch', 'mullaghmore', 'biarritz', 'somo', 'carcavelos', 'sandvik', 'hashpoint', 'ngor', 'caverock', 'canggu', 'nihiwatu', 'bawa', 'launion', 'miyazaki', 'midigama', 'waao', 'pastapoint', 'oneeye', 'noosaheads', 'burleighheads', 'shipsternbluff', 'thebox', 'cactus', 'restaurants', 'shipwreckbay', 'sunsetcliffs', 'sanonofre', 'cardiffreef', 'oceansidepier', 'venturapoint', 'countyline', 'pleasurepoint', 'lindamar', 'windansea', 'elporto', 'zuma', 'sebastianinlet', 'cocoabeach', 'wrightsville', 'virginiabeach', 'longbeachny', 'narragansett', 'manasquan', 'jaws', 'rockypoint', 'queens', 'makaha', 'scorpionbay', 'sanmiguel', 'troncones', 'elzonte', 'lasflores', 'olliespoint', 'nosara', 'bocasbluff', 'lobitos', 'iquique', 'matanzas', 'saquarema', 'noronha', 'praiadorosa', 'guincho', 'sagres', 'pantin', 'rodiles', 'capbreton', 'easkey', 'porthcawl', 'saltburn', 'scheveningen', 'sylt', 'klitmoller', 'hoddevik', 'killerpoint', 'safi', 'dakhla', 'sealpoint', 'muizenberg', 'newpier', 'tofo', 'hiltonbeach', 'hollowtrees', 'bingin', 'medewi', 'tland', 'krui', 'kata', 'ikumi', 'baler', 'chickens', 'winkipop', 'crescenthead', 'duranbah', 'maroubra', 'bondi', 'manly', 'gnaraloo', 'redbluff', 'yallingup', 'stclair', 'makorori', 'fitzroybeach', 'nahariya', 'akko', 'batgalim', 'atlit', 'habonim', 'nahsholim', 'beithanania', 'michmoret', 'beityanai', 'sironit', 'poleg', 'herzliya', 'maravi', 'bananabeach', 'batyam', 'palmachim', 'ashdod', 'ashkelon'];
export const ONBOARDING_PICKS = ['trestles', 'pipeline', 'jbay', 'uluwatu', 'nazare', 'snapper', 'mundaka'];

export const HOUR_LABELS = ['5a', '7a', '9a', '11a', '1p', '3p', '5p', '7p'];
export const HOUR_INDICES = [5, 7, 9, 11, 13, 15, 17, 19];
export const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
